==  基础
<<_options>>中所做的规定以及<<_registered_extensions>>中指定的扩展展示了本规范具备的功能。所有以gpkg_*开头的表、视图，以及本标准中指定的存储瓦片的用户数据表，都应该只有规定的列和表约束。存储要素的用户数据表中除了有这些规定的列，还可能有其他列。本标准中所有的表名和列名都应该使用小写。

=== 核心

每个*GeoPackage*和*GeoPackage SQLite*都应该实现附属条款中定义的核心功能以及本条款中的需求陈述。

==== SQLite 容器

SQLite软件库提供了一个自包含的、单文件、跨平台的、服务器无关的、事务性的、开源的RDBMS（关系数据库管理系统）容器。
为了使用SQLite软件库，GeoPackage规范定义了一个SQL数据库schema。
使用SQLite作为GeoPackage的基础简化了GeoPackage文件的生产、分发和使用，同时确保了Geopackage文件中的数据完整性。

“自包含”是指容器软件几乎不需要外部库或操作系统的支持。
 “单文件”是指在支持文件系统的计算平台中，容器在没有被任何软件打开时，在一个文件系统中只由一个独立文件构成。
“跨平台”指的是一个计算平台中创建和装载数据的容器文件，可能在另一个平台中被使用和更新，即使这两个平台位于不同的操作系统、文件系统甚至有不同的字节顺序（endian）约定。
 “服务器无关”指的是RDBMS容器的实现不需要任何中间服务器进程，就能被应用软件直接访问。
 “事务性”是指在程序崩溃、操作系统崩溃以及断电的情况下，RDBMS仍能确保对容器内数据的所有修改都具备 原子性(Atomicity）、一致性（Consistency）、隔离性（Isolation）和持久性（Durability）。

===== 数据

====== 文件格式

:req1_foot1: footnote:[SQLite version 4 (reference B25), which will be an alternative to version 3, not a replacement thereof, was not available when this specification was written. See Future Work clause in Annex B.]
:req1_foot2: footnote:[SQLite is in the public domain (see http://www.sqlite.org/copyright.html)]
:req2_foot1: footnote:[With SQLite versions 3.7.17 and later this value MAY be set with the "PRAGMA application_id=1196437808;" SQL statement, where 1196437808 is the 32-bit integer value of 0x47503130. With earlier versions of SQLite the application id can be set by writing the byte sequence 0x47, 0x50, 0x31, 0x30 at offset 68 in the SQLite database file (see http://www.sqlite.org/fileformat2.html#database_header for details).]


[requirement]
一个GeoPackage应该是一个 http://www.sqlite.org/[SQLite] <<5>>数据库文件，该数据库文件应使用 http://sqlite.org/fileformat2.html[3.x版本的SQLite文件格式] <<6>> <<7>>。
GeoPackage文件用ASCII格式 <<B4>>打开的前16个字节应该包含“SQLite format 3” {req1_foot1} 字符串。 {req1_foot2}

[requirement]
GeoPackage的SQLite数据库头（header）中，平台ID（application id）字段应该包含0x47503130（ASCII转码后为“GP10”）来表明文件为GeoPackage 1.0版本。{req2_foot1}

GeoPackage的最大存储空间约为140TB。在实际应用写文件的时候，因受到文件系统的影响，存储空间可能更小。很多移动设备的外部存储卡需要使用FAT32格式化，而FAT32文件系统也限制了GeoPackage单个文件的最大存储空间为4GB。

====== 文件扩展名

[requirement]
GeoPackage文件的扩展名为“*.gpkg”。

推荐扩展的GeoPackage文件使用扩展名“*.gpkx”，但GeoPackage规范并不做规定。

====== 文件内容

[requirement]
GeoPackage文件应该只包含数据要素、SQL元素、以及GeoPackage扩展，按照本标准要求，GeoPackage扩展应该带有“gpkg”作者名字。

为了保证应用程序之间最大的互操作性，GeoPackage文件不应包含本标准之外的数据要素（表或列）、SQL元素（数据类型，索引，约束或触发器）、以及扩展。
本规范中的扩展GeoPackage文件（Extended GeoPackages）是指SQLite数据库不仅使用了GeoPackage规范中规定的基本元素，还对这些元素进行了扩展。

[requirement]
GeoPackage数据表中的列仅可以使用<<table_column_data_types>>中规定的数据类型进行声明。

[[table_column_data_types]]
.GeoPackage 数据类型
[cols=",,,,,",options="header"]
|=======================================================================
|数据类型             | 大小与说明
|BOOLEAN              | 标识true或false的布尔值，在SQLite中存储为INTEGER类型，0表示true，1标识false
|TINYINT              | 8位补码表示的整数。在SQLite中存储为INTEGER类型，取值范围为[-128, 127]
|SMALLINT             | 16位补码表示的整数。在SQLite中存储为INTEGER类型，取值范围为[-32768, 32767]
|MEDIUMINT            | 32位补码表示的整数。在SQLite中存储为INTEGER类型，取值范围为[-2147483648, 2147483647] 
|INT, INTEGER         | 64位补码表示的整数。在SQLite中存储为INTEGER类型，取值范围为[-9223372036854775808, 9223372036854775807] 
|FLOAT                | IEEE 32位浮点数。在SQLite中存储为REAL类型，取值需要能被4个字节的IEEE浮点数表示
|DOUBLE, REAL         | IEEE 64位浮点数。在SQLite中存储为REAL类型
|TEXT{(maxchar_count)}| UTF-8或UTF-16编码的变长字符串，编码类型取决于PRAGMA encoding指令（参见：http://www.sqlite.org/pragma.html#pragma_encoding）。maxchar_count是可选的，它限定了字符串长度。如果未指定，则字符串长度是无限的。限制字符串长度是为了更好的表达信息，当字符串过长时，应用程序可能会把字符串截断。定义maxchar_count使应用程序能够根据字符串长度上限进行最佳处理。在SQLite中存储为TEXT类型
|BLOB{(max_size)}     |变长的二进制数据。max_size是可选的，它限定了数据的二进制长度。如果未指定，则长度是无限的。数据大小提供了信息参考。定义max_size使应用程序能够根据数据大小上限进行最佳处理。在SQLite中存储为BLOB类型
|<geometry_type_name> | 几何对象（Geometry）根据<<_geometry_encoding>> 进行编码。 <geometry type_name> 是符合2.1.3条款的<<geometry_types>>所列的其中一个几何类型，或是符合3.1.2条款和 <<extension_geometry_encoding>>的用户自定义几何类型。XY、XYZ、XYM和XYZM类型的几何对象使用的是同一数据类型。在SQLite中存储为BLOB类型
|DATE                 | ISO-8601标准的日期字符串，字符串格式为YYYY-MM-DD，使用UTF-8或UTF-16编码。参见TEXT类型。在SQLite中存储为TEXT类型
|DATETIME             | ISO-8601标准的日期/时间字符串，字符串格式为YYYY-MM-DDTHH：MM：SS.SSSZ，T用作分隔符，后缀Z表示DATETIME为协调世界时（UTC）,字符串使用UTF-8或UTF-16编码。参见TEXT类型。在SQLite中存储为TEXT类型
|=======================================================================

====== 文件完整性

[requirement]
对GeoPackage文件中运行SQLite的PRAGMA integrity_check命令，应该返回“ok”。

[requirement]
对GeoPackage文件中运行SQLite的PRAGMA foreign_key_check命令，不传参数时应该返回空的结果集，表示该GeoPackage文件的所有外键（foreign key）都有效。

===== API

[[api_sql]]
====== 结构化查询语言（SQL）

:req4_foot1: footnote:[New applications should use the latest available SQLite version software <<8>>]

[requirement]
GeoPackage的SQLite配置应该通过 http://www.sqlite.org/download.html[SQLite 3.x版本] <<6>> 的软件API，提供对GeoPackage内容的SQL访问方式。{req4_foot1}

====== 每个GPKG的SQLite配置

http://www.sqlite.org/download.html[SQLite] <<8>> 库有许多http://www.sqlite.org/compile.html[编译]和http://www.sqlite.org/pragma.html[运行] 时参数，在针对不同用途配置SQLite时可能被使用。
GeoPackage规范中的元素在运行时依赖于SQLite功能的可用性，本条款规定了编译和运行时，哪些参数可以使用，哪些参数不允许使用。

[requirement]
每个GeoPackge的SQLite配置都应该符合<<every_gpkg_sqlite_config_table>>中指定的SQLite编译和运行时参数说明。

[[every_gpkg_sqlite_config_table]]
.每个GeoPackage的SQLite配置
[cols=",,,",options="header",]
|=======================================================================
|Setting |参数 |应该 / 不应该 |Discussion
|compile |SQLITE_OMIT_* |不应该 |不应该包括任何 http://www.sqlite.org/compile.html#omitfeatures 中的OMIT参数
|run |PRAGMA foreign_keys |不应该 (关闭) |外键约束用来维持GeoPackage引用的完整性
|=======================================================================

[[spatial_ref_sys]]
==== 空间参考系统

===== 数据

[[spatial_ref_sys_data_table_definition]]
====== 表的定义

[requirement]
GeoPackage应该包含一个`gpkg_spatial_ref_sys`表，`gpkg_spatial_ref_sys`表必须符合 1.1.2.1.1 <<spatial_ref_sys_data_table_definition>>、表 <<gpkg_spatial_ref_sys_cols>> 和表<<gpkg_spatial_ref_sys_sql>>的规定。

表`gpkg_spatial_ref_sys`是标准SQL schema中描述简单要素（参见下面的<<sfsql_intro>> 条款）的第一个部分。它包含的坐标参考系定义被GeoPackage的`gpkg_contents` 和 `gpkg_geometry_columns`表引用，来将用户表中的矢量、瓦片数据与地球上的真实位置联系起来。

`gpkg_geometry_columns`表包含了SQL/MM (ISO 13249-3) <<12>>中规定的最少列，如下面的表<<gpkg_spatial_ref_sys_cols>> 所示，这些列包含了定义空间参考系所需的数据。
这个表的视图（Views）被用来使 http://www.iso.org/iso/home/store/catalogue_ics/catalogue_detail_ics.htm?csnumber=53698[SQL/MM] <<12>> (参见 表<<sqlmm_gpkg_spatial_ref_sys_sql>>)和OGC http://portal.opengeospatial.org/files/?artifact_id=25354[Simple Features SQL] <<9>><<10>><<11>> (Table 21) 规范保持兼容。

[[gpkg_spatial_ref_sys_cols]]
.空间参考系统表的定义
[cols=",,,",options="header",]
|=======================================================================
|Column Name |Column Type |Column Description |Null |Key
|`srs_name` |TEXT |空间参考系统（SRS）的名称|no |
|`srs_id` |INTEGER |GeoPackage中，SRS的唯一ID|no |PK
|`organization` |TEXT |定义SRS的组织的名称（不区分大小写），例如EPSG 或 epsg|no |
|`organization_coordsys_id` |INTEGER |由`organization`组织分配SRS数字ID|no |
|`definition` |TEXT |描述SRS的Well-known Text（WKT） <<32>>|no |
|`description` |TEXT |SRS的描述|yes |
|=======================================================================

参见 <<gpkg_spatial_ref_sys_sql>>.

====== 表数据的取值

表gpkg_spatial_ref_sys中，表示WKT值的列应该定义几何要素和栅格瓦片所使用的空间坐标系（SRS），当SRS未知时表示为 undefined（参见<<_requirement-11>>）。WKT的值应该由<<32>> 条款7中指定的EBNF syntax构成，应该包含可选的<authority> EBNF entities，非WGS-84的WKT值应该包含可选的 <to wgs84> EBNF entities。WKT值可能会省略可选的 <to wgs84> 和 <twin axes>  EBNF entities。任何指定的<authority>中（比如<<13>><<14>>），都可能获取到EBNF的名称和数值。例如，通过<<spatial_ref_sys_data_values_default>>测试方法的第(3)步的返回值，就可以测试WGS-84的定义，WGS-84的定义参见<<_requirement-11>>：

[requirement]
GeoPackage中的表`gpkg_spatial_ref_sys`应该包含至少3条记录，一条记录表示 http://www.google.com/search?as_q=WGS-84[WGS-84] <<15>>坐标系，该记录的organization为http://www.epsg.org/Geodetic.html[EPSG] 或 epsg <<B3>>，`organization_coordsys_id` 为 http://www.epsg-registry.org/report.htm?type=selection&entity=urn:ogc:def:crs:EPSG::4326&reportDetail=long&title=WGS%2084&style=urn:uuid:report-style:default-with-code&style_name=OGP%20Default%20With%20Code[4326] <<13>><<14>>；一条记录表示未定义的笛卡尔坐标系，该记录的`srs_id`值为-1，`organization`值为“NONE”，`organization_coordsys_id`值为-1，`definition`值为“undefined”；一条记录表示未定义的地理坐标系，该记录的`srs_id`值为0，`organization`值为“NONE”，`organization_coordsys_id`值为0，`definition`值为“undefined”

[requirement]
GeoPackage中的表`gpkg_spatial_ref_sys`应该包含Geopackage中的要素和瓦片用到的所有空间坐标系。

==== 内容

===== 数据

====== 表定义

[requirement]
GeoPackage应该包含一个`gpkg_contents`表，`gpkg_contents`表必须符合表 <<gpkg_contents_cols>> 和表<<gpkg_contents_sql>>的规定。

Geopackage中的空间数据是可访问和（或）更新的，表`gpkg_contents`的目的就是提供具有可识别性和描述性的信息，以便于应用程序将这些数据以更直观简洁的方式在用户面前展示出来。

[[gpkg_contents_cols]]
.内容表或视图的定义
[cols=",,,,,",options="header",]
|=======================================================================
|列名 |类型 |描述 |Null |默认值 |Key
|`table_name` |TEXT |瓦片或要素表的名字|no | |PK
|`data_type` |TEXT |存储在表中的数据类型，“features”表示<<features>>类型，“tiles”表示<<tiles>>类型，或是一个自定义值，表示扩展的Geopackage中其他类型的数据 |no | |
|`identifier` |TEXT |table_name的内容标识符（如短名称）|yes | |
|`description` |TEXT |table_name的内容描述|yes |“” |
|`last_change` |DATETIME |ISO 8601格式的时间戳，格式为'%Y-%m-%dT%H:%M:%fZ'，可通过strftime函数获取当前时间。|no |`strftime('%Y-%m-%dT%H:%M:%fZ', 'now')` |
|`min_x` |DOUBLE |table_name表中所有数据的边界框的最小 x 值|yes | |
|`min_y` |DOUBLE |table_name表中所有数据的边界框的最小 y 值|yes | |
|`max_x` |DOUBLE |table_name表中所有数据的边界框的最大 x 值|yes | |
|`max_y` |DOUBLE |table_name表中所有数据的边界框的最大 y 值|yes | |
|`srs_id` |INTEGER |空间参考系ID：参见`gpkg_spatial_ref_sys.srs_id`; 当`data_type` 为features时,应该与`gpkg_geometry_columns.srs_id`匹配;当`data_type`为tiles时, 应该与`gpkg_tile_matrix_set.srs_id`匹配。|yes | |FK
|=======================================================================

表`gpkg_contents`的目的是提供GeoPackage文件中所有地理空间数据的列表。
`data_type`列指定了地理空间数据的类型。
Bounding box(`min_x`, `min_y`, `max_x`, `max_y`)提供了详实的边界框（而不是必要的最小边界）。
当`srs_id`列的值表示的是地理坐标系（CRS）时，边界框的min/max x/y值的单位是度；当`srs_id`列的值表示的时投影坐标系（CRS）时，边界框的min/max x/y值的单位由该坐标系决定。

参见 <<gpkg_contents_sql>>.

====== 表中数据值 

[requirement]
表`gpkg_contents`的`table_name`列的取值应该是一个SQLite表名或视图名。

:req13_foot1: footnote:[The following statement selects an ISO 8601timestamp value using the SQLite strftime function: SELECT (strftime('%Y-%m-%dT%H:%M:%fZ','now')).]
[requirement]
表`gpkg_contents`的`last_change`列的取值应该符合 http://www.iso.org/iso/catalogue_detail?csnumber=40874[ISO 8601] <<29>> 规范，应该是一个包含UTC 小时, 分钟, 秒，以及秒的小数部分的完整的日期字符串，并应该带有‘Z’ (‘zulu’)后缀来标识时间为协调世界时（UTC）。{req13_foot1}

[requirement]
表`gpkg_contents`的`srs_id`列的值应该与表`gpkg_spatial_ref_sys`的`srs_id`列的值对应。
