非官方个发广告费== 基础

<<_options>>中所做的规定以及<<_registered_extensions>>中指定的扩展展示了本规范具备的功能。所有以gpkg_*开头的表、视图，以及本标准中指定的存储瓦片的用户数据表，都应该只有规定的列和表约束。存储要素的用户数据表中除了有这些规定的列，还可能有其他列。本标准中所有的表名和列名都应该使用小写。

=== 核心

每个*GeoPackage*和*GeoPackage SQLite*都应该实现附属条款中定义的核心功能以及本条款中的需求陈述。

==== SQLite 容器

SQLite软件库提供了一个自包含的、单文件、跨平台的、服务器无关的、事务性的、开源的RDBMS（关系数据库管理系统）容器。
为了使用SQLite软件库，GeoPackage规范定义了一个SQL数据库schema。
使用SQLite作为GeoPackage的基础简化了GeoPackage文件的生产、分发和使用，同时确保了Geopackage文件中的数据完整性。

“自包含”是指容器软件几乎不需要外部库或操作系统的支持。
 “单文件”是指在支持文件系统的计算平台中，容器在没有被任何软件打开时，在一个文件系统中只由一个独立文件构成。
“跨平台”指的是一个计算平台中创建和装载数据的容器文件，可能在另一个平台中被使用和更新，即使这两个平台位于不同的操作系统、文件系统甚至有不同的字节顺序（endian）约定。
 “服务器无关”指的是RDBMS容器的实现不需要任何中间服务器进程，就能被应用软件直接访问。
 “事务性”是指在程序崩溃、操作系统崩溃以及断电的情况下，RDBMS仍能确保对容器内数据的所有修改都具备 原子性(Atomicity）、一致性（Consistency）、隔离性（Isolation）和持久性（Durability）。

===== 数据

====== 文件格式

:req1_foot1: footnote:[SQLite version 4 (reference B25), which will be an alternative to version 3, not a replacement thereof, was not available when this specification was written. See Future Work clause in Annex B.]
:req1_foot2: footnote:[SQLite is in the public domain (see http://www.sqlite.org/copyright.html)]
:req2_foot1: footnote:[With SQLite versions 3.7.17 and later this value MAY be set with the "PRAGMA application_id=1196437808;" SQL statement, where 1196437808 is the 32-bit integer value of 0x47503130. With earlier versions of SQLite the application id can be set by writing the byte sequence 0x47, 0x50, 0x31, 0x30 at offset 68 in the SQLite database file (see http://www.sqlite.org/fileformat2.html#database_header for details).]


[requirement]
一个GeoPackage应该是一个 http://www.sqlite.org/[SQLite] <<5>>数据库文件，该数据库文件应使用 http://sqlite.org/fileformat2.html[3.x版本的SQLite文件格式] <<6>> <<7>>。
GeoPackage文件用ASCII格式 <<B4>>打开的前16个字节应该包含“SQLite format 3” {req1_foot1} 字符串。 {req1_foot2}

[requirement]
GeoPackage的SQLite数据库头（header）中，平台ID（application id）字段应该包含0x47503130（ASCII转码后为“GP10”）来表明文件为GeoPackage 1.0版本。{req2_foot1}

GeoPackage的最大存储空间约为140TB。在实际应用写文件的时候，因受到文件系统的影响，存储空间可能更小。很多移动设备的外部存储卡需要使用FAT32格式化，而FAT32文件系统也限制了GeoPackage单个文件的最大存储空间为4GB。

====== 文件扩展名

[requirement]
GeoPackage文件的扩展名为“*.gpkg”。

推荐扩展的GeoPackage文件使用扩展名“*.gpkx”，但GeoPackage规范并不做规定。

====== 文件内容

[requirement]
GeoPackage文件应该只包含数据要素、SQL元素、以及GeoPackage扩展，按照本标准要求，GeoPackage扩展应该带有“gpkg”作者名字。

为了保证应用程序之间最大的互操作性，GeoPackage文件不应包含本标准之外的数据要素（表或列）、SQL元素（数据类型，索引，约束或触发器）、以及扩展。
本规范中的扩展GeoPackage文件（Extended GeoPackages）是指SQLite数据库不仅使用了GeoPackage规范中规定的基本元素，还对这些元素进行了扩展。

[requirement]
GeoPackage数据表中的列仅可以使用<<table_column_data_types>>中规定的数据类型进行声明。

[[table_column_data_types]]
.GeoPackage 数据类型
[cols=",,,,,",options="header"]
|=======================================================================
|数据类型             | 大小与说明
|BOOLEAN              | 标识true或false的布尔值，在SQLite中存储为INTEGER类型，0表示true，1标识false
|TINYINT              | 8位补码表示的整数。在SQLite中存储为INTEGER类型，取值范围为[-128, 127]
|SMALLINT             | 16位补码表示的整数。在SQLite中存储为INTEGER类型，取值范围为[-32768, 32767]
|MEDIUMINT            | 32位补码表示的整数。在SQLite中存储为INTEGER类型，取值范围为[-2147483648, 2147483647] 
|INT, INTEGER         | 64位补码表示的整数。在SQLite中存储为INTEGER类型，取值范围为[-9223372036854775808, 9223372036854775807] 
|FLOAT                | IEEE 32位浮点数。在SQLite中存储为REAL类型，取值需要能被4个字节的IEEE浮点数表示
|DOUBLE, REAL         | IEEE 64位浮点数。在SQLite中存储为REAL类型
|TEXT{(maxchar_count)}| UTF-8或UTF-16编码的变长字符串，编码类型取决于PRAGMA encoding指令（参见：http://www.sqlite.org/pragma.html#pragma_encoding）。maxchar_count是可选的，它限定了字符串长度。如果未指定，则字符串长度是无限的。限制字符串长度是为了更好的表达信息，当字符串过长时，应用程序可能会把字符串截断。定义maxchar_count使应用程序能够根据字符串长度上限进行最佳处理。在SQLite中存储为TEXT类型
|BLOB{(max_size)}     |变长的二进制数据。max_size是可选的，它限定了数据的二进制长度。如果未指定，则长度是无限的。数据大小提供了信息参考。定义max_size使应用程序能够根据数据大小上限进行最佳处理。在SQLite中存储为BLOB类型
|<geometry_type_name> | 几何对象（Geometry）根据<<_geometry_encoding>> 进行编码。 <geometry type_name> 是符合2.1.3条款的<<geometry_types>>所列的其中一个几何类型，或是符合3.1.2条款和 <<extension_geometry_encoding>>的用户自定义几何类型。XY、XYZ、XYM和XYZM类型的几何对象使用的是同一数据类型。在SQLite中存储为BLOB类型
|DATE                 | ISO-8601标准的日期字符串，字符串格式为YYYY-MM-DD，使用UTF-8或UTF-16编码。参见TEXT类型。在SQLite中存储为TEXT类型
|DATETIME             | ISO-8601标准的日期/时间字符串，字符串格式为YYYY-MM-DDTHH：MM：SS.SSSZ，T用作分隔符，后缀Z表示DATETIME为协调世界时（UTC）,字符串使用UTF-8或UTF-16编码。参见TEXT类型。在SQLite中存储为TEXT类型
|=======================================================================

====== 文件完整性

[requirement]
对GeoPackage文件中运行SQLite的PRAGMA integrity_check命令，应该返回“ok”。

[requirement]
对GeoPackage文件中运行SQLite的PRAGMA foreign_key_check命令，不传参数时应该返回空的结果集，表示该GeoPackage文件的所有外键（foreign key）都有效。

===== API

[[api_sql]]
====== 结构化查询语言（SQL）

:req4_foot1: footnote:[New applications should use the latest available SQLite version software <<8>>]

[requirement]
GeoPackage的SQLite配置应该通过 http://www.sqlite.org/download.html[SQLite 3.x版本] <<6>> 的软件API，提供对GeoPackage内容的SQL访问方式。{req4_foot1}

====== 每个GPKG的SQLite配置

http://www.sqlite.org/download.html[SQLite] <<8>> 库有许多http://www.sqlite.org/compile.html[编译]和http://www.sqlite.org/pragma.html[运行] 时参数，在针对不同用途配置SQLite时可能被使用。
GeoPackage规范中的元素在运行时依赖于SQLite功能的可用性，本条款规定了编译和运行时，哪些参数可以使用，哪些参数不允许使用。

[requirement]
每个GeoPackge的SQLite配置都应该符合<<every_gpkg_sqlite_config_table>>中指定的SQLite编译和运行时参数说明。

[[every_gpkg_sqlite_config_table]]
.每个GeoPackage的SQLite配置
[cols=",,,",options="header",]
|=======================================================================
|Setting |参数 |应该 / 不应该 |Discussion
|compile |SQLITE_OMIT_* |不应该 |不应该包括任何 http://www.sqlite.org/compile.html#omitfeatures 中的OMIT参数
|run |PRAGMA foreign_keys |不应该 (关闭) |外键约束用来维持GeoPackage引用的完整性
|=======================================================================

[[spatial_ref_sys]]
==== 空间参考系统

===== 数据

[[spatial_ref_sys_data_table_definition]]
====== 表的定义

[requirement]
A GeoPackage SHALL include a `gpkg_spatial_ref_sys` table per clause 1.1.2.1.1 <<spatial_ref_sys_data_table_definition>>, Table <<gpkg_spatial_ref_sys_cols>> and Table <<gpkg_spatial_ref_sys_sql>>.geopackage规范应包括gpkg_spatial_ref_sys表的每项条款

A table named `gpkg_spatial_ref_sys` is the first component of the standard SQL schema for simple features described in clause <<sfsql_intro>> below.
The coordinate reference system definitions it contains are referenced by the GeoPackage `gpkg_contents` and `gpkg_geometry_columns` tables to relate the vector and tile data in user tables to locations on the earth.
名为gpkg_spatial_ref_sys表是标准SQL模式的第一个部分。在下面的2.1.1中描述了简单功能。坐标参考系统的定义，它包含引用的geopackage gpkg_contents和gpkg_geometry_columns表，以及与表关联的用用户表中的矢量和瓦片数据在地球上定位。

The `gpkg_spatial_ref_sys` table includes at a minimum the columns specified in SQL/MM (ISO 13249-3) <<12>> and shown in <<gpkg_spatial_ref_sys_cols>> below containing data that defines spatial reference systems.
Views of this table MAY be used to provide compatibility with the http://www.iso.org/iso/home/store/catalogue_ics/catalogue_detail_ics.htm?csnumber=53698[SQL/MM] <<12>> (see <<sqlmm_gpkg_spatial_ref_sys_sql>>) and OGC http://portal.opengeospatial.org/files/?artifact_id=25354[Simple Features SQL] <<9>><<10>><<11>> (Table 21) specifications.
该gpkg_spatial_ref_sys表至少包括在SQL / MM（ISO13249-3）规定，和在下表3中展示出的列，表3中包含定义空间参考系统的数据。 此表的视图可以用于提供与SQL /毫米的兼容性（表19）和SQL（表20）规定的OGC简单要素。

[[gpkg_spatial_ref_sys_cols]]
.空间参考系统表的定义
[cols=",,,",options="header",]
|=======================================================================
|Column Name |Column Type |Column Description |Null |Key
|`srs_name` |TEXT |Human readable name of this SRS 空间参考系统名字|no |
|`srs_id` |INTEGER |Unique identifier for each Spatial Reference System within a GeoPackage GeoPackage规范内每个空间参考系统唯一标识|no |PK
|`organization` |TEXT |Case-insensitive name of the defining organization e.g. EPSG or epsg 定义的组织不区分大小写，例如EPSG or epsg|no |
|`organization_coordsys_id` |INTEGER |Numeric ID of the Spatial Reference System assigned by the organization 由组织分配的空间参考系统的数字ID|no |
|`definition` |TEXT |Well-known Text <<32>> Representation of the Spatial Reference System 由文字标示的著名空间参考系统|no |
|`description` |TEXT |Human readable description of this SRS 空间参考系统描述|yes |
|=======================================================================

See <<gpkg_spatial_ref_sys_sql>>.

====== 表中数据值

Definition column WKT values in the gpkg_spatial_ref_sys table SHALL define the Spatial Reference Systems used by feature geometries and tile images, unless these SRS are unknown and therefore undefined as specified in <<_requirement-11>>. Values SHALL be constructed per the EBNF syntax in <<32>> clause 7. Values SHALL include optional <authority> EBNF entities. Values for SRS other than WGS-84 SHOULD include optional <to wgs84> EBNF entities. Values MAY omit optional <to wgs84> and <twin axes> EBNF entities. EBNF name and number values MAY be obtained from any specified <authority>, e.g. <<13>><<14>>. For example, see the return value in <<spatial_ref_sys_data_values_default>> Test Method step (3) used to test the definition for WGS-84 per <<_requirement-11>>:
在gpkg_spatial_ref_sys表中定义的WKT列值，将定义使用了集合要素和图片的空间参考系统。除非这些SRS是未知的，因此不需要在要求11中指定。值应该按第7条款中的EBNF语法构建。值应包括可选的<局> EBNF实体。SRS除了WGS-84外，应包括可选的< WGS84 > EBNF实体值。值可以忽略可选的< WGS84 >和< < WGS84双轴> EBNF实体。EBNF的名字和号码的值可以从任何指定的<局>获得。例如，看到A.1.1.2.1.2试验方法步骤的返回值，用于测试每个请求11 的WGS-84坐标定义。

[requirement]
The `gpkg_spatial_ref_sys` table in a GeoPackage SHALL contain a record for
organization http://www.epsg.org/Geodetic.html[EPSG] or epsg <<B3>> and `organization_coordsys_id` http://www.epsg-registry.org/report.htm?type=selection&entity=urn:ogc:def:crs:EPSG::4326&reportDetail=long&title=WGS%2084&style=urn:uuid:report-style:default-with-code&style_name=OGP%20Default%20With%20Code[4326] <<13>><<14>> for http://www.google.com/search?as_q=WGS-84[WGS-84] <<15>>, a record with an `srs_id` of -1, an organization of “NONE”, an `organization_coordsys_id` of -1, and definition “undefined” for undefined Cartesian coordinate reference systems, and a record with an `srs_id` of 0, an organization of “NONE”, an `organization_coordsys_id` of 0, and definition “undefined” for undefined geographic coordinate reference systems.在符合geopackage规范的gpkg_spatial_ref_sys表中，应当包括组织EPSG或epsg和WGS-84的organization_coordsys_id 4326记录，一个为-1的srs_id记录，一个“无”组织，一个为-1 的organization_coordsys_id组织，为未定义的笛卡尔坐标参考系定义“未定义”， 一个为0的srs_id记录，一个“无”组织，一个为0 的organization_coordsys_id组织，为未定义的地理坐标参考系统定义“未定义”。

[requirement]
The `gpkg_spatial_ref_sys` table in a GeoPackage SHALL contain records to define all spatial reference systems used by features and tiles in a GeoPackage.在符合geopackage规范的gpkg_spatial_ref_sys表中，应包含一些记录，去定义在GeoPackage中被被要素和瓦片使用的所有空间参考系统

==== 内容

===== 数据

====== 表定义

[requirement]
A GeoPackage file SHALL include a `gpkg_contents` table per table <<gpkg_contents_cols>> and <<gpkg_contents_sql>>.geopackage包括的gpkg_contents表在本章节1.1.3.1.1，表4和表21中进行了描述。

The purpose of the `gpkg_contents` table is to provide identifying and descriptive information that an application can display to a user in a menu of geospatial data that is available for access and/or update.该gpkg_contents表的作用是提供一种识别和描述性信息，这种信息指的是应用程序可以以菜单的形式向用户展示可访问或更新的地理空间数据。

[[gpkg_contents_cols]]
.Contents Table or View Definition
[cols=",,,,,",options="header",]
|=======================================================================
|Column Name |Type |Description 描述 |Null |Default |Key
|`table_name` |TEXT |视图或要素表的名字|no | |PK
|`data_type` |TEXT |Type of data stored in the table:. “features” per clause <<features>>, “tiles” per clause <<tiles>>, or an implementer-defined value for other data tables per clause in an Extended GeoPackage. 存储在表中的数据类型，“要素”在章节2.1.2.1.1中做了描述，“视图”在章节2.2.2.1.1中做了描述，扩展GeoPackage其他数据表定义的值 |no | |
|`identifier` |TEXT |A human-readable identifier (e.g. short name) for the table_name content 为table_name内容标识符（如短名称）|yes | |
|`description` |TEXT |A human-readable description for the table_name content 为table_name内容的描述|yes |“” |
|`last_change` |DATETIME |timestamp value in ISO 8601 format as defined by the strftime function '%Y-%m-%dT%H:%M:%fZ' format string applied to the current time |no |`strftime('%Y-%m-%dT%H:%M:%fZ', 'now')` |
|`min_x` |DOUBLE |Bounding box minimum easting or longitude for all content in table_name  table_name表所有选项中,X坐标或经度的最小值|yes | |
|`min_y` |DOUBLE |Bounding box minimum northing or latitude for all content in table_name  table_name表所有选项中， Y坐标或纬度的最小值|yes | |
|`max_x` |DOUBLE |Bounding box maximum easting or longitude for all content in table_name  table_name表所有选项中， X坐标或经度的最大值|yes | |
|`max_y` |DOUBLE |Bounding box maximum northing or latitude for all content in table_name  table_name表所有选项中， Y坐标或纬度的最大值|yes | |
|`srs_id` |INTEGER |Spatial Reference System ID: `gpkg_spatial_ref_sys.srs_id`; when `data_type` is features, SHALL also match `gpkg_geometry_columns.srs_id`; When data_type is tiles, SHALL also match gpkg_tile_matrix_set.srs.id  空间参考系统ID：gpkg_spatial_ref_sys.srs_id；当数据类型为features 时，ID默认值为 gpkg_geometry_columns.srs_id；当数据类型为tiles 时，ID默认值为gpkg_tile_matrix_set.srs.id|yes | |FK
|=======================================================================

The `gpkg_contents` table is intended to provide a list of all geospatial contents in a GeoPackage.
The `data_type` specifies the type of content.
The bounding box (`min_x`, `min_y`, `max_x`, `max_y`) provides an informative bounding box (not necessarily minimum bounding box) of the content.
If the `srs_id` column value references a geographic coordinate reference system (CRS), then the min/max x/y values are in decimal degrees; otherwise, the srs_id references a projected CRS and the min/max x/y values are in the units specified by that CRS.
gpkg_contents_table表的目的是按geopackage规范以列表的方式提供所有空间数据，data_type指定了内容的类型。边界框（min_x，min_y，max_x，max_y）提供了边界框（不一定是最小的边界框）内容信息。如果srs_id列值为地理坐标参考系统（CRS），那么最小/最大x/ y的值是十进制数；否则，srs_id引用引用的事CRS，最小/最大x / y的值是由指定的CRS单位确定。

See <<gpkg_contents_sql>>.

====== 表中数据值 

[requirement]
The `table_name` column value in a `gpkg_contents` table row SHALL contain the name of a SQLite table or view.  在gpkg_contents表的行中，table_name列的值应包含SQLite数据库表或视图的名称。
:req13_foot1: footnote:[The following statement selects an ISO 8601timestamp value using the SQLite strftime function: SELECT (strftime('%Y-%m-%dT%H:%M:%fZ','now')).]
[requirement]
Values of the `gpkg_contents` table `last_change` column SHALL be in http://www.iso.org/iso/catalogue_detail?csnumber=40874[ISO 8601] <<29>> format containing a complete date plus UTC hours, minutes, seconds and a decimal fraction of a second, with a ‘Z’ (‘zulu’) suffix indicating UTC. {req13_foot1}
gpkg_contents表的last_change列的值应为ISO 8601 [ 29 ]格式，这种格式包含了完整的日期加UTC小时，分钟，秒和秒的小数部分，用“Z”（'zulu”）的后缀表示UTC。
[requirement]
Values of the `gpkg_contents` table `srs_id` column SHALL reference values in the `gpkg_spatial_ref_sys` table `srs_id` column.
gpkg_contents表的srs_id列的值应该参考gpkg_spatial_ref_sys表的srs_id列的值。
