== 选择

The optional capabilities specified in this clause depend on the required capabilities specified in clause <<_base>> above. 在本条款中指定的可选功能取决于上面章节<<_base>> ，指定的需要的功能。
Each subclause of this clause defines an indivisible module of functionality that can be used in GeoPackages. These modules are referred to as options. 本条款中的每个子条款定义的不可分割的功能模块，可用于geopackages ，这些模块被称为选项。
GeoPackages可能使用本节中定义的一个或多个选项。GeoPackages可以忽略未使用的选项表。
As a minimum, a GeoPackage SHALL contain one user data table as defined by the Features or Tiles options in clauses <<features>> and <<tiles>> respectively.  作为最低要求，GeoPackage 应该包含一个由Features 或 Tiles选项定义的用户数据表，该用户数据表在<<features>> 和<<tiles>> 中分别进行了定义。

[requirement]
A GeoPackage SHALL contain features per clause <<features>> and/or tiles per clause <<tiles>> and row(s) in the `gpkg_contents` table with lowercase `data_type` column values of “features” and/or “tiles” describing the user data tables.
geopackage规范应包含 <<features>> 条款中的每个要素，<<tiles>> 条款中的每个瓦片以及`gpkg_contents` 表中data_type列的值为小写的“features” 或 “tiles”的行，这些行描述了用户数据表。 

