[[tiles]]
=== 瓦片

==== 瓦片矩阵介绍


有各种各样 关于 在瓦片金字塔存储，索引，访问和描述瓦片 的商业和开源规则。
不幸的是，在这个领域，无论国家或国际规范的标准 还没有普遍的共识。
此外，不同的图像文件格式有不同的表示能力，包括不同的自我描述性元数据。 


瓦片存储数据/元数据模型和在下面描述的公约，支持在GeoPackage中以两种方式直接使用瓦片。
首先，它们指定了已有的应用程序如何在现有的表的基础上，可以创建的数据/元数据模型的SQL视图，SQL视图遵循不同的接口约定。
其次，他们包含和呈现了 关于 数据集和记录 级别 充足的元数据信息 允许使用 GeoPackage 数据的应用不需要解析所有存储的影像，就可以发现它的特性 
存储GeoPackage 瓦片数据，并且具 有这些信息访问权限 应用程序，必须要存储充分的元数据来支持它的未来的这种用途。

The GeoPackage 瓦片存储数据模型 可以直接 作为 SQLite 数据库的数据表得以实现，这中方法性能最佳;
或者 在已有的瓦片存储表上建立SQL 视图，这种方法能达到最大的适应性和低耦合 ，从而能被广泛的实施.


:tiles_intro_foot1: footnote:[Images of multiple MIME types MAY be stored in given table. For example, in a tiles table, image/png format tiles COULD be used for transparency where there is no data on the tile edges, and image/jpeg format tiles COULD be used for storage efficiency where there is image data for all pixels. Images of multiple bit depths of the same MIME type MAY also be stored in a given table, for example image/png tiles in both 8 and 24 bit depths.]

GeoPackage CAN 存储多种栅格和瓦片金字塔数据集合在同一个容器的不同表和视图中.
{tiles_intro_foot1} 
“Tile pyramid”  瓦片金字塔指 不同缩放级别 不同空间范围 相同分辨率 这样一些瓦片和瓦片自身的数据 所构成的金字塔型的结构 。
“Tile matrix” 在一个指定的缩放级别上，瓦片的行和列都具有相同的空间范围和分辨率 。
“Tile matrix set” 瓦片金字塔中层级结构.（？？）

The tables or views that implement the GeoPackage tile store data / metadata model are described and discussed individually 
in the following subsections.
GeoPackage 瓦片存储数据或元数据的模型的具体实现的表和视图 会在下面的章节中分别阐述。

==== 内容

===== 数据

====== 内容表 – 瓦片列

[requirement]
 `gpkg_contents` 表必须对于每个瓦片金字塔用户数据表或视图 都对应包含一条记录， 这条记录中要包含 名为`data_type` 列，且列值为 “tiles”.

[[zoom_levels]]
==== Zoom Levels

GeoPackage中, 缩放级别是从0到n的整数，用来表示瓦片矩阵集中的不同的瓦片矩阵图层，瓦片矩阵集中包含了具有较小的空间范围和更清晰的空间分辨率的瓦片。
Adjacent zoom levels immediately preceed or follow each other and differ by a value of 1.
相邻的缩放级别递增或递减，值相差1.
Pixel sizes are real numbers in the terrain units of the spatial reference system of a tile image
 specifying the dimensions of the real world area represented by one pixel.
 ？？？像素大小是一个真实数字 以瓦片图像所在的空间参考系统下的 地形的单位表示，该单位定义了 一个像素所代表的在现实世界中真实区域的大小。
Pixel size MAY vary by a constant factor or by different factors or intervals 
between some or all adjacent zoom levels in a tile matrix set.
在瓦片矩阵集中在某些或所有相邻的缩放级别之间，像素大小可以是以一个常量变化，或者以不同的因子和间隔 变化。
In the commonly used "zoom times two" convention, pixel sizes vary by a factor of 2 between all adjacent zoom levels,
 as shown in the example in <<tiles_factor2_example_appendix>>.
 在使用最普遍的"zoom times two"（缩放两倍）惯例中，不同缩放级别的像素大小以两倍因子变化 如 <<tiles_factor2_example_appendix>> 例子中所展示的那样。
 
Other "zoom other intervals" conventions use different factors or irregular intervals with pixel sizes 
chosen for intuitive cartographic representation of raster data,
 or to coincide with the original pixel size of commonly used global image products.
See WMTS <<16>> Annex E for additional examples of both conventions.
其它 "zoom other intervals" 惯例 为了栅格数据的直观的图像显示 或 为了 与 全球通用的图像产品的原始坐标大小保持一致 ，在像素大小 使用不同的因子和不规则的间隔。

===== 数据

====== 两倍缩放

:zoom_times_two_foot1: footnote:[See clause 3.2.1.1.1 for use of other zoom levels as a registered extensions.]
[requirement]
In a GeoPackage that contains a tile pyramid user data table that contains tile data, by default {zoom_times_two_foot1}, 
zoom level pixel sizes for that table SHALL vary by a factor of 2 between adjacent zoo levels in the tile matrix metadata table.
在GeoPackage中，瓦片金字塔用户数据表包含瓦片数据，默认{zoom_times_two_foot1}，表中相邻缩放级别的像素大小必须要按照 瓦片矩阵元数据表中的 2倍因子变化。
[[tile_enc_png]]
==== Tile Encoding PNG

===== 数据

====== MIME Type PNG

:png_req_foot1: footnote:[See Clause 3.2.2 regarding use of the WebP alternative tile MIME type as a registered extension.]
[requirement]
在GeoPackage中，瓦片金字塔数据表中的瓦片数据如果不是 http://www.ietf.org/rfc/rfc2046.txt[MIME type] http://www.jpeg.org/public/jfif.pdf[image/jpeg] <<17>><<18>><<19>>类型，那么默认就是 http://www.iana.org/assignments/media-types/index.html[MIME type] http://libpng.org/pub/png/[image/png] <<20>><<21>>类型。{png_req_foot1}



[[tile_enc_jpeg]]
==== Tile Encoding JPEG

===== 数据

====== MIME Type JPEG

:jpg_req_foot1: footnote:[See Clause 3.2.2 regarding use of the WebP alternative tile MIME type as a registered extension.]
[requirement]
在GeoPackage中，瓦片金字塔数据表中的瓦片数据如果不是 http://www.iana.org/assignments/media-types/index.html[MIME type] http://libpng.org/pub/png/[image/png] <<20>><<21>>类型，那么默认就是 http://www.ietf.org/rfc/rfc2046.txt[MIME type] http://www.jpeg.org/public/jfif.pdf[image/jpeg] <<17>><<18>><<19>>类型。{jpg_req_foot1}

==== 瓦片矩阵集合

===== 数据

[[tile_matrix_set_data_table_definition]]
====== 表定义

[requirement]
包含瓦片金字塔数据表的Geopackage文件，必须有一个符合<<tile_matrix_set_data_table_definition>>条款、表<<gpkg_tile_matrix_set_cols>> 和表<<gpkg_tile_matrix_set_sql>>规定的`gpkg_tile_matrix_set`表或视图，

[[gpkg_tile_matrix_set_cols]]
.瓦片矩阵集合的表或视图定义
[cols=",,,,,",options="header",]
|=======================================================================
|Column Name |Column Type |Column Description |Null |Default |Key
|`table_name` |TEXT |瓦片金字塔数据表名 |no | | PK, FK
|`srs_id` |INTEGER | 空间参考系ID: gpkg_spatial_ref_sys.srs_id |no |  |FK
|`min_x` |DOUBLE |table_name 中所有瓦片的Bounding box 的最小 easting or longitude |no | |
|`min_y` |DOUBLE |table_name 中所有瓦片的Bounding box minimum northing or latitude  |no | |
|`max_x` |DOUBLE |table_name 中所有瓦片的Bounding box maximum easting or longitude  |no | |
|`max_y` |DOUBLE |table_name 中所有瓦片的Bounding box maximum northing or latitude |no | |
|=======================================================================

在 gpkg_tile_matrix_set 表或可更新的视图中为瓦片金字塔用户数据表中的所有瓦片定义了最小的bounding box (min_x, min_y, max_x, max_y)
和空间参考系统(srs_id)。

参见 <<gpkg_tile_matrix_set_sql>>.

[[clause_tile_matrix_set_table_data_values]]
====== 表数据值

The minimum bounding box defined in the gpkg_tile_matrix_set table or view for a tile pyramid user data table SHALL be exact 
so that the bounding box coordinates for individual tiles in a tile pyramid MAY be calculated
 based on the column values for the user data table in the gpkg_tile_matrix table or view.  For example,
 because GeoPackages use the upper left tile origin convention defined in clause <<clause_tile_matrix_table_data_values>> below, 
 the gpkg_tile_matrix_set (min_x, max_y) ordinate is the upper-left corner of tile (0,0) for all zoom levels in
 a table_name tile pyramid user data table.
gpkg_tile_matrix_set表或视图中 为瓦片金字塔用户数据表 定义的最小的bounding box 必须是 确定的 以便对于瓦片金字塔中的单个tiles 的bounding box的坐标
都可以被计算。计算时基于gpkg_tile_matrix表或视图中的用户数据表的列值。例如，GeoPackages 使用的 在下面 条款 <<clause_tile_matrix_table_data_values>> 中所描述的惯例
即 左上的瓦片原点。在 table_name 列中的的瓦片金字塔用户数据表 中的所有缩放级别下，gpkg_tile_matrix_set (min_x, max_y) 坐标 (0,0)瓦片的左上角。

[requirement]
Values of the `gpkg_tile_matrix_set` `table_name` column SHALL reference values in th gpkg_contents table_name column for
 rows with a data type of "tiles".
`gpkg_tile_matrix_set` 表的 `table_name`的值必须是 gpkg_contents 的行中的 数据类型为"tiles" 时 table_name 列的引用
[requirement]
The gpkg_tile_matrix_set table or view SHALL contain one row record for each tile pyramid user data table.
gpkg_tile_matrix_set  表或视图 必须对每个瓦片金字塔用户数据表 都对应包含一行记录

[requirement]
Values of the `gpkg_tile_matrix_set` `srs_id` column SHALL reference values in the `gpkg_spatial_ref_sys` `srs_id` column.
`gpkg_tile_matrix_set`中的`srs_id` 列的值必须是引用的 `gpkg_spatial_ref_sys`的`srs_id`的值。

[[tile_matrix]]
==== 瓦片矩阵

===== 数据

[[tile_matrix_data_table_definition]]
====== 表的定义

[requirement]
包含瓦片金字塔数据表的GeoPackage，应包含一个`gpkg_tile_matrix`表或视图，`gpkg_tile_matrix`表或视图要符合2.2.7.1.1 <<tile_matrix_data_table_definition>>、表<<gpkg_tile_matrix_cols>>以及表 <<gpkg_tile_matrix_sql>>的规定。

[[gpkg_tile_matrix_cols]]
.瓦片矩阵元数据表或视图的定义
[cols=",,,,",options="header",]
|=======================================================================
|Column Name |Column Type |Column Description |Null  |Key
|`table_name` |TEXT |瓦片金字塔用户数据表的表名 |no |PK, FK
|`zoom_level` |INTEGER | 0 <= `zoom_level` <= max_level for `table_name` |no |PK
|`matrix_width` |INTEGER |在当前缩放级别下，瓦片矩阵的列数。（>=1）|1 |
|`matrix_height` |INTEGER |在当前缩放级别下，瓦片矩阵的行数。（>=1） |1 |
|`tile_width` |INTEGER |在当前缩放级别下，瓦片的宽度（以像素为单位）。（>=1） |no |
|`tile_height` |INTEGER |在当前缩放级别下，瓦片的高度（以像素为单位。（>=1）|no |
|`pixel_x_size` |DOUBLE |以t_table_name 的srid单位表示，默认单位是米（srid为0时）。（>=0）|no |
|`pixel_y_size` |DOUBLE |以t_table_name 的srid单位表示，默认单位是米（srid为0时）。（>=0）|no |
|=======================================================================

`gpkg_tile_matrix`表或可更新的视图记录了每个tiles表中每个缩放级别下的tile matrix的结构。GeoPackage不仅允许包含正方形的瓦片，也允许包含长方形的瓦片（例如，为了更好的表达两极地区）。瓦片金字塔允许有这样的缩放级别：相邻级别分辨率相差2倍、相邻级别分辨率变化不规律、或者相邻级别分辨率变化虽然规律，但不是相差2倍。

See <<gpkg_tile_matrix_sql>>

[[clause_tile_matrix_table_data_values]]
====== 表数据的取值

[requirement]
`gpkg_tile_matrix`表中的 `table_name` 列的值，应该与`gpkg_contents`表中，`data_type`值为“tiles”的行的table_name值一一对应。

[requirement]
`gpkg_tile_matrix`表或视图应该针对每一个缩放级别包含一行记录，该行记录对应的瓦片金字塔数据或视图应该包含一个或多个瓦片。

在瓦片金字塔数据表中，缩放级别中没有瓦片时，`gpkg_tile_matrix`表或视图中也可以有对应的记录行。

:tile_matrix_meta_foot1: footnote:[GeoPackage applications MAY query the gpkg_tile_matrix table or the tile pyramid user data table to determine the minimum and maximum zoom levels for a given tile pyramid table.]

GeoPackages 遵循最常用的惯例，如 http://portal.opengeospatial.org/files/?artifact_id=35326[WMTS] <<16>>所指定，瓦片的原点在左上，缩放到“whole world”级别 下对应的比例尺是最小比例尺，对应的缩放级别为 0 级 {tile_matrix_meta_foot1}。
瓦片坐标（0,0）通常指在任何缩放级别下 tile matrix的左上角，该左上角的瓦片可以不是实际存在的。

[requirement]
`gpkg_tile_matrix`表中`zoom_level`这一列的值不能为负值

[requirement]
`gpkg_tile_matrix`表中`matrix_width`这一列的值必须大于0

[requirement]
`gpkg_tile_matrix`表中`matrix_height`这一列的值必须大于0

[requirement]
`gpkg_tile_matrix`表中`tile_width` 这一列的值必须大于0

[requirement]
`gpkg_tile_matrix`表中`tile_height` 这一列的值必须大于0

[requirement]
`gpkg_tile_matrix`表中`pixel_x_size`这一列的值必须大于0

[requirement]
`gpkg_tile_matrix`表中`pixel_ y _size`这一列的值必须大于0

[requirement]
`gpkg_tile_matrix`表中，当`zoom_level`列升序排列时，`pixel_x_siz`e 和`pixel_y_size`列的值应该为降序排列。

:sparse_tiles_foot1: footnote:[GeoPackage applications MAY query a tile pyramid user data table to determine which tiles are available at each zoom level.]
:sparse_tiles_foot2: footnote:[GeoPackage applications that insert, update, or delete tile pyramid user data table tiles row records are responsible for maintaining the corresponding descriptive contents of the gpkg_tile_matrix_metadata table.]
:sparse_tiles_foot3: footnote:[The `gpkg_tile_matrix_set` table contains coordinates that define a bounding box as the exact stated spatial extent for all tiles in a tile (matrix set) table. If the geographic extent of the image data contained in tiles at a particular zoom level is within but not equal to this bounding box, then the non-image area of matrix edge tiles must be padded with no-data values, preferably transparent ones.]

0级别或者其它缩放级别可能有瓦片，也可能没有瓦片。 {sparse_tiles_foot1}
这意味着`tile matrix set` 可以是稀疏的，例如，在一个确定的缩放级别 下，并不是所有位置都包含瓦片。
{sparse_tiles_foot2}这并不影响`gpkg_contents`表中该缩放级别对应记录的空间范围（由min_x、min_y、max_x、max_y列的值确定），也不影响`gpkg_tile_matrix_set`表中该缩放级别对应记录的精确空间范围（由min_x、min_y、max_x、max_y列的值确定），更不会影响该缩放级别的瓦片矩阵宽和高。 {sparse_tiles_foot3}

[[tiles_user_tables]]
==== 瓦片金字塔数据表

===== 数据

[[tiles_user_tables_data_table_definition]]
====== 表定义

[requirement]
GeoPackage中的每个瓦片矩阵集（tile matrix set）必须存储在独立的瓦片金字塔数据表或可更新的视图（view）中。这些数据表或视图必须具备唯一的名称，必须包含类型为INTGER的名为“id”的列，该列必须有'PRIMARY KEY AUTOINCREMENT'列约束。参见2.2.8.1.1 <<tiles_user_tables_data_table_definition>>、<<example_tiles_table_cols>> 以及 <<example_tiles_table_insert_sql>>中的规定。

[[example_tiles_table_cols]]
.瓦片金字塔数据表或视图定义
[cols=",,,,,",options="header",]
|=======================================================================
|Column Name |Column Type |Column Description |Null |Default |Key
|`id` |INTEGER |自动增长的主键（primary key）  |no | |PK
|`zoom_level` |INTEGER |min(zoom_level) <= `zoom_level` <= max(zoom_level) for `t_table_name` |no |0 |UK
|`tile_column` |INTEGER |大于0，小于gpkg_tile_matrix表的matrix_width值 |no |0 |UK
|`tile_row` |INTEGER |大于0，小于gpkg_tile_matrix表的matrix_height值 |no |0 |UK
|`tile_data` |BLOB | 条款<<tile_enc_png>>, <<tile_enc_jpeg>>, <<tile_enc_webp>>, <<tile_enc_tiff>>, <<tile_enc_nitf>>中定义的影像 MIME 类型。 |no | |
|=======================================================================

参见 <<example_tiles_table_sql>>.

====== 表数据取值

:tile_data_foot1: footnote:[A GeoPackage is not required to contain any tile pyramid user data tables. Tile pyramid user data tables in a GeoPackage MAY be empty.]

:tile_data_foot1_ref: footnote:[The zoom_level / tile_column / tile_row unique key is automatically indexed, and allows tiles to be selected and accessed by "z, x, y", a common convention used by some implementations.  This table / view definition MAY also allow tiles to be selected based on a spatially indexed bounding box in a separate metadata table.]

每个瓦片金字塔用户数据表或视图 {tile_data_foot1}都可以包含多个瓦片矩阵，这些瓦片矩阵对应第0级或更多缩放级别，每个缩放级别对应不同的空间分辨率（地图比例尺）。

[requirement]
在GeoPackage文件中，`gpkg_tile_matrix`(tm)表中的每个不同的`table_name`所对应的瓦片金字塔（tp）数据表中， `zoom_level`列的值应该符合以下条件：min(tm.zoom_level) <= tp.zoom_level <= max(tm.zoom_level)

[requirement]
在GeoPackage文件中，`gpkg_tile_matrix` (tm)表中的每个不同的`table_name`所对应的瓦片金字塔（tp）数据表中， tile_column列的值应该符合以下条件：当tm和tp的`zoom_level` 列值相同时，0 <= tp.tile_column <= tm.matrix_width – 1。

[requirement]
在GeoPackage文件中，`gpkg_tile_matrix` (tm)表中的每个不同的`table_name`所对应的瓦片金字塔（tp）数据表中， tile_row列的值应该符合以下条件：当tm和tp的`zoom_level` 列值相同时，0 <= tp.tile_row <= tm.matrix_height – 1。

同一缩放级别的所有瓦片都具有相同的`pixel_x_size`和`pixel_y_size`值，缩放级别对应瓦片表，以及瓦片表的`pixel_x_size`和`pixel_y_size`值是在gpkg_tile_matrix表中指定的。{tile_data_foot1_ref}