[[tiles]]
=== 瓦片

==== 瓦片矩阵介绍

There are a wide variety of commercial and open source conventions for storing, indexing, accessing and describing tiles in tile pyramids. Unfortunately, no applicable existing consensus, national or international specifications have standardized practices in this domain. In addition, various image file formats have different representational capabilities, and include different self-descriptive metadata. 
有各种各样用于存储，索引，访问和描述金字塔的商业和开源规则。不幸的是，在这个领域，还没有符合现行共识，国家或国际规范的标准实例。此外，不同的图像文件格式有不同的表示能力，包括不同的自我描述性元数据。 

The tile store data / metadata model and convention described below support direct use of tiles in a GeoPackage in two ways. First, they specify how existing application MAY create SQL Views of the data /metadata model on top of existing application tables that that follow different interface conventions. Second, they include and expose enough metadata information at both the dataset and record level to allow applications that use GeoPackage data to discover its characteristics without having to parse all of the stored images. Applications that store GeoPackage tile data, which are presumed to have this information available, SHALL store sufficient metadata to enable its intended use.
瓦片存储数据/元数据模型和在下面描述的公约，支持用两种方式直接使用符合GeoPackage规范的瓦片。首先，它们指定了如何用现有应用程序在现有的应用程序表上，创建的数据/元数据模型的SQL视图，SQL视图遵循不同的接口约定。

The GeoPackage tile store data model MAY be implemented directly as SQL tables in a SQLite database for maximum performance, or as SQL views on top of tables in an existing SQLite tile store for maximum adaptability and loose coupling to enable widespread implementation.

:tiles_intro_foot1: footnote:[Images of multiple MIME types MAY be stored in given table. For example, in a tiles table, image/png format tiles COULD be used for transparency where there is no data on the tile edges, and image/jpeg format tiles COULD be used for storage efficiency where there is image data for all pixels. Images of multiple bit depths of the same MIME type MAY also be stored in a given table, for example image/png tiles in both 8 and 24 bit depths.]

A GeoPackage CAN store multiple raster and tile pyramid data sets in different tables or views in the same container.
{tiles_intro_foot1} “Tile pyramid” refers to the concept of pyramid structure of tiles of different spatial extent an resolution at different zoom levels, and the tile data itself.
“Tile matrix” refers to rows and columns of tiles tha all have the same spatial extent and resolution at a particular zoom level.
“Tile matrix set” refers to the definitio of a tile pyramid’s tiling structure.

The tables or views that implement the GeoPackage tile store data / metadata model are described and discussed individually in the following subsections.

==== Contents

===== Data

====== Contents Table – Tiles Row

[requirement]
The `gpkg_contents` table SHALL contain a row with a `data_type` column value of “tiles” for each tile pyramid user data table or view.

[[zoom_levels]]
==== Zoom Levels

In a GeoPackage, zoom levels are integers in sequence from 0 to n that identify tile matrix layers in a tile matrix set that contain tiles of decreasing spatial extent and finer spatial resolution.
Adjacent zoom levels immediately preceed or follow each other and differ by a value of 1.
Pixel sizes are real numbers in the terrain units of the spatial reference system of a tile image specifying the dimensions of the real world area represented by one pixel.
Pixel size MAY vary by a constant factor or by different factors or intervals between some or all adjacent zoom levels in a tile matrix set.
In the commonly used "zoom times two" convention, pixel sizes vary by a factor of 2 between all adjacent zoom levels, as shown in the example in <<tiles_factor2_example_appendix>>.
Other "zoom other intervals" conventions use different factors or irregular intervals with pixel sizes chosen for intuitive cartographic representation of raster data, or to coincide with the original pixel size of commonly used global image products.
See WMTS <<16>> Annex E for additional examples of both conventions.

===== Data

====== Zoom Times Two

:zoom_times_two_foot1: footnote:[See clause 3.2.1.1.1 for use of other zoom levels as a registered extensions.]
[requirement]
In a GeoPackage that contains a tile pyramid user data table that contains tile data, by default {zoom_times_two_foot1}, zoom level pixel sizes for that table SHALL vary by a factor of 2 between adjacent zoo levels in the tile matrix metadata table.

[[tile_enc_png]]
==== Tile Encoding PNG

===== Data

====== MIME Type PNG

:png_req_foot1: footnote:[See Clause 3.2.2 regarding use of the WebP alternative tile MIME type as a registered extension.]
[requirement]
In a GeoPackage that contains a tile pyramid user data table that contains tile data that is not http://www.ietf.org/rfc/rfc2046.txt[MIME type] http://www.jpeg.org/public/jfif.pdf[image/jpeg] <<17>><<18>><<19>>, by default SHALL store that tile data in http://www.iana.org/assignments/media-types/index.html[MIME type] http://libpng.org/pub/png/[image/png] <<20>><<21>>. {png_req_foot1}

[[tile_enc_jpeg]]
==== Tile Encoding JPEG

===== Data

====== MIME Type JPEG

:jpg_req_foot1: footnote:[See Clause 3.2.2 regarding use of the WebP alternative tile MIME type as a registered extension.]
[requirement]
In a GeoPackage that contains a tile pyramid user data table that contains tile data that is not http://www.iana.org/assignments/media-types/index.html[MIME type] http://libpng.org/pub/png/[image/png] <<20>><<21>>, by default SHALL store that tile data in http://www.ietf.org/rfc/rfc2046.txt[MIME type] http://www.jpeg.org/public/jfif.pdf[image/jpeg] <<17>><<18>><<19>>. {jpg_req_foot1}

==== Tile Matrix Set

===== Data

[[tile_matrix_set_data_table_definition]]
====== Table Definition

[requirement]
A GeoPackage that contains a tile pyramid user data table SHALL contain  `gpkg_tile_matrix_set` table or view per <<tile_matrix_set_data_table_definition>>, <<gpkg_tile_matrix_set_cols>> and <<gpkg_tile_matrix_set_sql>>.

[[gpkg_tile_matrix_set_cols]]
.Tile Matrix Set Table or View Definition
[cols=",,,,,",options="header",]
|=======================================================================
|Column Name |Column Type |Column Description |Null |Default |Key
|`table_name` |TEXT |Tile Pyramid User Data Table Name |no | | PK, FK
|`srs_id` |INTEGER | Spatial Reference System ID: gpkg_spatial_ref_sys.srs_id |no |  |FK
|`min_x` |DOUBLE |Bounding box minimum easting or longitude for all content in table_name |no | |
|`min_y` |DOUBLE |Bounding box minimum northing or latitude for all content in table_name |no | |
|`max_x` |DOUBLE |Bounding box maximum easting or longitude for all content in table_name |no | |
|`max_y` |DOUBLE |Bounding box maximum northing or latitude for all content in table_name |no | |
|=======================================================================

The gpkg_tile_matrix_set table or updateable view defines the minimum bounding box (min_x, min_y, max_x, max_y) and spatial reference system (srs_id) for all content in a tile pyramid user data table.

See <<gpkg_tile_matrix_set_sql>>.

[[clause_tile_matrix_set_table_data_values]]
====== Table Data Values

The minimum bounding box defined in the gpkg_tile_matrix_set table or view for a tile pyramid user data table SHALL be exact so that the bounding box coordinates for individual tiles in a tile pyramid MAY be calculated based on the column values for the user data table in the gpkg_tile_matrix table or view.  For example, because GeoPackages use the upper left tile origin convention defined in clause <<clause_tile_matrix_table_data_values>> below, the gpkg_tile_matrix_set (min_x, max_y) ordinate is the upper-left corner of tile (0,0) for all zoom levels in a table_name tile pyramid user data table.

[requirement]
Values of the `gpkg_tile_matrix_set` `table_name` column SHALL reference values in th gpkg_contents table_name column for rows with a data type of "tiles".

[requirement]
The gpkg_tile_matrix_set table or view SHALL contain one row record for each tile pyramid user data table.

[requirement]
Values of the `gpkg_tile_matrix_set` `srs_id` column SHALL reference values in the `gpkg_spatial_ref_sys` `srs_id` column.

[[tile_matrix]]
==== 瓦片矩阵

===== 数据

[[tile_matrix_data_table_definition]]
====== 表的定义

[requirement]
包含瓦片金字塔数据表的GeoPackage，应包含一个‘gpkg_tile_matrix’表或视图，‘gpkg_tile_matrix’表或视图要符合2.2.7.1.1 <<tile_matrix_data_table_definition>>、表<<gpkg_tile_matrix_cols>>以及表 <<gpkg_tile_matrix_sql>>的规定。

[[gpkg_tile_matrix_cols]]
.瓦片矩阵元数据表或视图的定义
[cols=",,,,",options="header",]
|=======================================================================
|Column Name |Column Type |Column Description |Null  |Key
|`table_name` |TEXT |瓦片金字塔用户数据表的表名 |no |PK, FK
|`zoom_level` |INTEGER | 0 <= `zoom_level` <= max_level for `table_name` |no |PK
|`matrix_width` |INTEGER |在当前缩放级别下，瓦片矩阵的列数。（>=1）|1 |
|`matrix_height` |INTEGER |在当前缩放级别下，瓦片矩阵的行数。（>=1） |1 |
|`tile_width` |INTEGER |在当前缩放级别下，瓦片的宽度（以像素为单位）。（>=1） |no |
|`tile_height` |INTEGER |在当前缩放级别下，瓦片的高度（以像素为单位。（>=1）|no |
|`pixel_x_size` |DOUBLE |以t_table_name 的srid单位表示，默认单位是米（srid为0时）。（>=0）|no |
|`pixel_y_size` |DOUBLE |以t_table_name 的srid单位表示，默认单位是米（srid为0时）。（>=0）|no |
|=======================================================================

'gpkg_tile_matrix'表或可更新的视图记录了每个tiles表中每个缩放级别下的tile matrix的结构。GeoPackage不仅允许包含正方形的瓦片，也允许包含长方形的瓦片（例如，为了更好的表达两极地区）。瓦片金字塔允许有这样的缩放级别：相邻级别分辨率相差2倍、相邻级别分辨率变化不规律、或者相邻级别分辨率变化虽然规律，但不是相差2倍。

See <<gpkg_tile_matrix_sql>>

[[clause_tile_matrix_table_data_values]]
====== 表数据的取值

[requirement]
gpkg_tile_matrix表中的 table_name 列的值，应该与gpkg_contents表中，data_type值为“tiles”的行的table_name值一一对应。

[requirement]
gpkg_tile_matrix表或视图应该针对每一个缩放级别包含一行记录，该行记录对应的瓦片金字塔数据或视图应该包含一个或多个瓦片。

在瓦片金字塔数据表中，缩放级别中没有瓦片时，gpkg_tile_matrix表或视图中也可以有对应的记录行。

:tile_matrix_meta_foot1: footnote:[GeoPackage applications MAY query the gpkg_tile_matrix table or the tile pyramid user data table to determine the minimum and maximum zoom levels for a given tile pyramid table.]

GeoPackages 遵循最常用的惯例，如 http://portal.opengeospatial.org/files/?artifact_id=35326[WMTS] <<16>>所指定，瓦片的原点在左上，缩放到“whole world”级别 下对应的比例尺是最小比例尺，对应的缩放级别为 0 级 {tile_matrix_meta_foot1}。
瓦片坐标（0,0）通常指在任何缩放级别下 tile matrix的左上角，该左上角的瓦片可以不是实际存在的。

[requirement]
gpkg_tile_matrix表中zoom_level这一列的值不能为负值

[requirement]
gpkg_tile_matrix表中matrix_width这一列的值必须大于0

[requirement]
gpkg_tile_matrix表中matrix_height这一列的值必须大于0

[requirement]
gpkg_tile_matrix表中tile_width 这一列的值必须大于0

[requirement]
gpkg_tile_matrix表中tile_height 这一列的值必须大于0

[requirement]
gpkg_tile_matrix表中pixel_x_size这一列的值必须大于0

[requirement]
gpkg_tile_matrix表中pixel_ y _size这一列的值必须大于0

[requirement]
gpkg_tile_matrix表中，当zoom_level列升序排列时，pixel_x_size 和 pixel_y_size列的值应该为降序排列。

:sparse_tiles_foot1: footnote:[GeoPackage applications MAY query a tile pyramid user data table to determine which tiles are available at each zoom level.]
:sparse_tiles_foot2: footnote:[GeoPackage applications that insert, update, or delete tile pyramid user data table tiles row records are responsible for maintaining the corresponding descriptive contents of the gpkg_tile_matrix_metadata table.]
:sparse_tiles_foot3: footnote:[The `gpkg_tile_matrix_set` table contains coordinates that define a bounding box as the exact stated spatial extent for all tiles in a tile (matrix set) table. If the geographic extent of the image data contained in tiles at a particular zoom level is within but not equal to this bounding box, then the non-image area of matrix edge tiles must be padded with no-data values, preferably transparent ones.]

0级别或者其它缩放级别可能有瓦片，也可能没有瓦片。 {sparse_tiles_foot1}
这意味着tile matrix set 可以是稀疏的，例如，在一个确定的缩放级别 下，并不是所有位置都包含瓦片。
{sparse_tiles_foot2}这并不影响gpkg_contents表中该缩放级别对应记录的空间范围（由min_x、min_y、max_x、max_y列的值确定），也不影响gpkg_tile_matrix_set表中该缩放级别对应记录的精确空间范围（由min_x、min_y、max_x、max_y列的值确定），更不会影响该缩放级别的瓦片矩阵宽和高。 {sparse_tiles_foot3}

[[tiles_user_tables]]
==== 瓦片金字塔数据表

===== 数据

[[tiles_user_tables_data_table_definition]]
====== 表定义

[requirement]
GeoPakage中的每个瓦片矩阵集（tile matrix set）必须存储在独立的瓦片金字塔数据表或可更新的视图（view）中。这些数据表或视图必须具备唯一的名称，必须包含类型为INTGER的名为“id”的列，该列必须有'PRIMARY KEY AUTOINCREMENT'列约束。参见2.2.8.1.1 <<tiles_user_tables_data_table_definition>>、<<example_tiles_table_cols>> 以及 <<example_tiles_table_insert_sql>>中的规定。

[[example_tiles_table_cols]]
.瓦片金字塔数据表或视图定义
[cols=",,,,,",options="header",]
|=======================================================================
|Column Name |Column Type |Column Description |Null |Default |Key
|`id` |INTEGER |自动增长的主键（primary key）  |no | |PK
|`zoom_level` |INTEGER |min(zoom_level) <= `zoom_level` <= max(zoom_level) for `t_table_name` |no |0 |UK
|`tile_column` |INTEGER |大于0，小于gpkg_tile_matrix表的matrix_width值 |no |0 |UK
|`tile_row` |INTEGER |大于0，小于gpkg_tile_matrix表的matrix_height值 |no |0 |UK
|`tile_data` |BLOB | 条款<<tile_enc_png>>, <<tile_enc_jpeg>>, <<tile_enc_webp>>, <<tile_enc_tiff>>, <<tile_enc_nitf>>中定义的影像 MIME 类型。 |no | |
|=======================================================================

参见 <<example_tiles_table_sql>>.

====== 表数据取值

:tile_data_foot1: footnote:[A GeoPackage is not required to contain any tile pyramid user data tables. Tile pyramid user data tables in a GeoPackage MAY be empty.]

:tile_data_foot1_ref: footnote:[The zoom_level / tile_column / tile_row unique key is automatically indexed, and allows tiles to be selected and accessed by "z, x, y", a common convention used by some implementations.  This table / view definition MAY also allow tiles to be selected based on a spatially indexed bounding box in a separate metadata table.]

每个瓦片金字塔用户数据表或视图 {tile_data_foot1}都可以包含多个瓦片矩阵，这些瓦片矩阵对应第0级或更多缩放级别，每个缩放级别对应不同的空间分辨率（地图比例尺）。

[requirement]
在GeoPackage文件中，gpkg_tile_matrix (tm)表中的每个不同的table_name所对应的瓦片金字塔（tp）数据表中， zoom_level列的值应该符合以下条件：min(tm.zoom_level) <= tp.zoom_level <= max(tm.zoom_level)

[requirement]
在GeoPackage文件中，gpkg_tile_matrix (tm)表中的每个不同的table_name所对应的瓦片金字塔（tp）数据表中， tile_column列的值应该符合以下条件：当tm和tp的`zoom_level` 列值相同时，0 <= tp.tile_column <= tm.matrix_width – 1。

[requirement]
在GeoPackage文件中，gpkg_tile_matrix (tm)表中的每个不同的table_name所对应的瓦片金字塔（tp）数据表中， tile_row列的值应该符合以下条件：当tm和tp的`zoom_level` 列值相同时，0 <= tp.tile_row <= tm.matrix_height – 1。

同一缩放级别的所有瓦片都具有相同的`pixel_x_size`和`pixel_y_size`值，缩放级别对应瓦片表，以及瓦片表的`pixel_x_size`和`pixel_y_size`值是在gpkg_tile_matrix表中指定的。{tile_data_foot1_ref}