[[tiles]]
=== 瓦片

==== 瓦片矩阵介绍

有关存储、索引、访问和描述金子塔中瓦片的商业和开源规则多种多样，然而，很不幸，在这个领域并没有形成标准的约定、国家标准或国际标准。
此外，不同的影像文件格式有不同的表述特性，也各自包含不同的自描述元数据。 

瓦片数据/元数据存储模型和约定从两个方面直接支撑GeoPackage文件中瓦片的使用。首先，现有应用中的数据表可能遵循的是其他接口约定，它们描述了如何在这些数据表的最顶层创建数据/元数据模型的SQL视图；其次，它们在数据集和记录的级别包含和暴露了大量元数据信息，从而允许应用程序在不解析所有影像的情况下，利用GeoPackage数据挖掘数据细节。

GeoPackage瓦片存储模型可以直接通过SQLite数据库中的SQL表实现，这种方法性能最高；也可以通过在已有SQLite瓦片存储中的数据表顶层，通过SQL视图实现，这种方法具有高适应性和低耦合的特征，更有利于标准的传播。

:tiles_intro_foot1: footnote:[Images of multiple MIME types MAY be stored in given table. For example, in a tiles table, image/png format tiles COULD be used for transparency where there is no data on the tile edges, and image/jpeg format tiles COULD be used for storage efficiency where there is image data for all pixels. Images of multiple bit depths of the same MIME type MAY also be stored in a given table, for example image/png tiles in both 8 and 24 bit depths.]

同一个容器中，GeoPackage可以在不通的数据表或视图中存储多个栅格和瓦片金字塔数据集。
{tiles_intro_foot1} 
“Tile pyramid（瓦片金字塔）”的概念中，不同缩放级别下的瓦片表示不同空间范围、具备不同分辨率，“Tile pyramid（瓦片金字塔）”也指瓦片数据本身。
“Tile matrix（瓦片矩阵）” 指的是某一缩放级别下，瓦片组成的行和列。该缩放级别中的这些瓦片表示相同的空间范围，具有相同的分辨率 。
“Tile matrix set（瓦片矩阵集合）”指的是瓦片金字塔层次结构的定义。

实现瓦片数据/元数据存储模型的表或视图，会在接下来的子章节中分别阐述和探讨。

==== 内容

===== 数据

====== 内容表 – 瓦片列

[requirement]
 `gpkg_contents` 表必须对于每个瓦片金字塔用户数据表或视图 都对应包含一条记录， 这条记录中要包含 名为`data_type` 列，且列值为 “tiles”.

[[zoom_levels]]
==== 缩放级别

在GeoPackage中,瓦片矩阵集中有不同级别的瓦片矩阵图层，缩放级别是指与瓦片矩阵图层相对应的从0到n的有序整形数字，用于标识不同的瓦片矩阵图层。随着缩放级别的递增，每个瓦片所代表的实际空间范围会变小，空间分辨率却会越高，图像也会更加清晰。
相邻缩放级别间递增或递减，值相差1。像素大小是一个真实数字，单位为瓦片图像空间参考系的地形单位，这个数字规定了一个像素所代表的现实世界区域大小。
在瓦片矩阵集的相邻的缩放级别间，像素大小可以按照固定倍率、不同倍率或间隔变化
在常用的“两倍缩放（zoom times two）”惯例中，所有相邻缩放级别的像素大小相差2倍，如下面<<tiles_factor2_example_appendix>> 中所展示的那样。
而在“其他缩放间隔（zoom other intervals）”惯例中，为了栅格数据直观的图像显示、以及与常用的全球影像产品中的原始像素大小保持一致，像素大小会按照不同倍率或不规则的间隔进行变化。
参见 WMTS <<16>> Annex E，这是两种惯例的附加示例。

===== 数据
====== 两倍缩放

:zoom_times_two_foot1: footnote:[See clause 3.2.1.1.1 for use of other zoom levels as a registered extensions.]
[requirement]
在一个有瓦片金字塔的GeoPackage中，默认情况下{zoom_times_two_foot1}，瓦片矩阵表中相邻缩放级别的像素大小相差2倍。

[[tile_enc_png]]
==== PNG瓦片编码格式

===== 数据

====== PNG MIME类型

:png_req_foot1: footnote:[See Clause 3.2.2 regarding use of the WebP alternative tile MIME type as a registered extension.]
[requirement]
在GeoPackage中，瓦片金字塔数据表中的瓦片数据如果不是 http://www.ietf.org/rfc/rfc2046.txt[MIME type] http://www.jpeg.org/public/jfif.pdf[image/jpeg] <<17>><<18>><<19>>类型，那么默认就是 http://www.iana.org/assignments/media-types/index.html[MIME type] http://libpng.org/pub/png/[image/png] <<20>><<21>>类型。{png_req_foot1}



[[tile_enc_jpeg]]
==== JPEG瓦片编码格式

===== 数据

====== JPEG MIME类型

:jpg_req_foot1: footnote:[See Clause 3.2.2 regarding use of the WebP alternative tile MIME type as a registered extension.]
[requirement]
在GeoPackage中，瓦片金字塔数据表中的瓦片数据如果不是 http://www.iana.org/assignments/media-types/index.html[MIME type] http://libpng.org/pub/png/[image/png] <<20>><<21>>类型，那么默认就是 http://www.ietf.org/rfc/rfc2046.txt[MIME type] http://www.jpeg.org/public/jfif.pdf[image/jpeg] <<17>><<18>><<19>>类型。{jpg_req_foot1}

==== 瓦片矩阵集

===== 数据

[[tile_matrix_set_data_table_definition]]
====== 表定义

[requirement]
包含瓦片金字塔数据表的Geopackage文件，必须有一个`gpkg_tile_matrix_set`表或视图，`gpkg_tile_matrix_set`表或视图需要符合<<tile_matrix_set_data_table_definition>>章节、表<<gpkg_tile_matrix_set_cols>> 和表<<gpkg_tile_matrix_set_sql>>的规定。

[[gpkg_tile_matrix_set_cols]]
.瓦片矩阵集合的表或视图定义
[cols=",,,,,",options="header",]
|=======================================================================
|Column Name |Column Type |Column Description |Null |Default |Key
|`table_name` |TEXT |瓦片金字塔数据表名 |no | | PK, FK
|`srs_id` |INTEGER | 空间参考系ID: gpkg_spatial_ref_sys.srs_id |no |  |FK
|`min_x` |DOUBLE |table_name表中所有数据的边界框的最小 x 值|no | |
|`min_y` |DOUBLE |table_name表中所有数据的边界框的最小 y 值|no | |
|`max_x` |DOUBLE |table_name表中所有数据的边界框的最大 x 值|no | |
|`max_y` |DOUBLE |table_name表中所有数据的边界框的最大 y 值|no | |
|=======================================================================

表gpkg_tile_matrix_set（或可更新视图）为瓦片金字塔数据表中的所有瓦片定义了最小的边界框(min_x, min_y, max_x, max_y)，以及空间参考系(srs_id)。

参见 <<gpkg_tile_matrix_set_sql>>.

[[clause_tile_matrix_set_table_data_values]]
====== 表数据值

瓦片金字塔数据表对应的表gpkg_tile_matrix_set（或可更新视图）定义的最小边界框必须是精确的。这样以来，根据表 gpkg_tile_matrix table 或视图中的数据表中的瓦片行列号，瓦片金字塔中独立瓦片的边界框坐标可以计算出来。
例如，因为Geopackage遵循左上角瓦片作为坐标原点的约定（参见<<clause_tile_matrix_table_data_values>>），所以，在表gpkg_tile_matrix_set的table_name列对应的瓦片金字塔数据表中，无论哪个缩放级别，(min_x, max_y)位置一定是的瓦片(0,0)的左上角坐标。

[requirement]
`gpkg_tile_matrix_set` 的 `table_name`列的值必须与表`gpkg_contents`中数据类型为"tiles"的记录的`table_name`列值一一对应。

[requirement]
针对每个瓦片金字塔数据表，gpkg_tile_matrix_set表或视图都必须包含一条记录。

[requirement]
`gpkg_tile_matrix_set`的`srs_id` 列的值必须与`gpkg_spatial_ref_sys`的`srs_id`列值一一对应。

[[tile_matrix]]
==== 瓦片矩阵

===== 数据

[[tile_matrix_data_table_definition]]
====== 表的定义

[requirement]
包含瓦片金字塔数据表的GeoPackage，应包含一个`gpkg_tile_matrix`表或视图，`gpkg_tile_matrix`表或视图要符合2.2.7.1.1 <<tile_matrix_data_table_definition>>、表<<gpkg_tile_matrix_cols>>以及表 <<gpkg_tile_matrix_sql>>的规定。

[[gpkg_tile_matrix_cols]]
.瓦片矩阵元数据表或视图的定义
[cols=",,,,",options="header",]
|=======================================================================
|Column Name |Column Type |Column Description |Null  |Key
|`table_name` |TEXT |瓦片金字塔用户数据表的表名 |no |PK, FK
|`zoom_level` |INTEGER | 0 <= `zoom_level` <= max_level for `table_name` |no |PK
|`matrix_width` |INTEGER |在当前缩放级别下，瓦片矩阵的列数。（>=1）|1 |
|`matrix_height` |INTEGER |在当前缩放级别下，瓦片矩阵的行数。（>=1） |1 |
|`tile_width` |INTEGER |在当前缩放级别下，瓦片的宽度（以像素为单位）。（>=1） |no |
|`tile_height` |INTEGER |在当前缩放级别下，瓦片的高度（以像素为单位。（>=1）|no |
|`pixel_x_size` |DOUBLE |以t_table_name 的srid单位表示，默认单位是米（srid为0时）。（>=0）|no |
|`pixel_y_size` |DOUBLE |以t_table_name 的srid单位表示，默认单位是米（srid为0时）。（>=0）|no |
|=======================================================================

`gpkg_tile_matrix`表或可更新的视图记录了每个tiles表中每个缩放级别下的tile matrix的结构。GeoPackage不仅允许包含正方形的瓦片，也允许包含长方形的瓦片（例如，为了更好的表达两极地区）。瓦片金字塔允许有这样的缩放级别：相邻级别分辨率相差2倍、相邻级别分辨率变化不规律、或者相邻级别分辨率变化虽然规律，但不是相差2倍。

See <<gpkg_tile_matrix_sql>>

[[clause_tile_matrix_table_data_values]]
====== 表数据的取值

[requirement]
`gpkg_tile_matrix`表中的 `table_name` 列的值，应该与`gpkg_contents`表中，`data_type`值为“tiles”的行的table_name值一一对应。

[requirement]
`gpkg_tile_matrix`表或视图应该针对每一个缩放级别包含一行记录，该行记录对应的瓦片金字塔数据或视图应该包含一个或多个瓦片。

在瓦片金字塔数据表中，缩放级别中没有瓦片时，`gpkg_tile_matrix`表或视图中也可以有对应的记录行。

:tile_matrix_meta_foot1: footnote:[GeoPackage applications MAY query the gpkg_tile_matrix table or the tile pyramid user data table to determine the minimum and maximum zoom levels for a given tile pyramid table.]

GeoPackages 遵循最常用的惯例，如 http://portal.opengeospatial.org/files/?artifact_id=35326[WMTS] <<16>>所指定，瓦片的原点在左上，缩放到“whole world”级别 下对应的比例尺是最小比例尺，对应的缩放级别为 0 级 {tile_matrix_meta_foot1}。
瓦片坐标（0,0）通常指在任何缩放级别下 tile matrix的左上角，该左上角的瓦片可以不是实际存在的。

[requirement]
`gpkg_tile_matrix`表中`zoom_level`这一列的值不能为负值

[requirement]
`gpkg_tile_matrix`表中`matrix_width`这一列的值必须大于0

[requirement]
`gpkg_tile_matrix`表中`matrix_height`这一列的值必须大于0

[requirement]
`gpkg_tile_matrix`表中`tile_width` 这一列的值必须大于0

[requirement]
`gpkg_tile_matrix`表中`tile_height` 这一列的值必须大于0

[requirement]
`gpkg_tile_matrix`表中`pixel_x_size`这一列的值必须大于0

[requirement]
`gpkg_tile_matrix`表中`pixel_ y _size`这一列的值必须大于0

[requirement]
`gpkg_tile_matrix`表中，当`zoom_level`列升序排列时，`pixel_x_size` 和`pixel_y_size`列的值应该为降序排列。

:sparse_tiles_foot1: footnote:[GeoPackage applications MAY query a tile pyramid user data table to determine which tiles are available at each zoom level.]
:sparse_tiles_foot2: footnote:[GeoPackage applications that insert, update, or delete tile pyramid user data table tiles row records are responsible for maintaining the corresponding descriptive contents of the gpkg_tile_matrix_metadata table.]
:sparse_tiles_foot3: footnote:[The `gpkg_tile_matrix_set` table contains coordinates that define a bounding box as the exact stated spatial extent for all tiles in a tile (matrix set) table. If the geographic extent of the image data contained in tiles at a particular zoom level is within but not equal to this bounding box, then the non-image area of matrix edge tiles must be padded with no-data values, preferably transparent ones.]

0级别或者其它缩放级别可能有瓦片，也可能没有瓦片。 {sparse_tiles_foot1}
这意味着`tile matrix set` 可以是稀疏的，例如，在一个确定的缩放级别 下，并不是所有位置都包含瓦片。
{sparse_tiles_foot2}这并不影响`gpkg_contents`表中该缩放级别对应记录的空间范围（由min_x、min_y、max_x、max_y列的值确定），也不影响`gpkg_tile_matrix_set`表中该缩放级别对应记录的精确空间范围（由min_x、min_y、max_x、max_y列的值确定），更不会影响该缩放级别的瓦片矩阵宽和高。 {sparse_tiles_foot3}

[[tiles_user_tables]]
==== 瓦片金字塔数据表

===== 数据

[[tiles_user_tables_data_table_definition]]
====== 表定义

[requirement]
GeoPackage中的每个瓦片矩阵集（tile matrix set）必须存储在独立的瓦片金字塔数据表或可更新的视图（view）中。这些数据表或视图必须具备唯一的名称，必须包含类型为INTGER的名为“id”的列，该列必须有'PRIMARY KEY AUTOINCREMENT'列约束。参见2.2.8.1.1 <<tiles_user_tables_data_table_definition>>、<<example_tiles_table_cols>> 以及 <<example_tiles_table_insert_sql>>中的规定。

[[example_tiles_table_cols]]
.瓦片金字塔数据表或视图定义
[cols=",,,,,",options="header",]
|=======================================================================
|Column Name |Column Type |Column Description |Null |Default |Key
|`id` |INTEGER |自动增长的主键（primary key）  |no | |PK
|`zoom_level` |INTEGER |min(zoom_level) <= `zoom_level` <= max(zoom_level) for `t_table_name` |no |0 |UK
|`tile_column` |INTEGER |大于0，小于gpkg_tile_matrix表的matrix_width值 |no |0 |UK
|`tile_row` |INTEGER |大于0，小于gpkg_tile_matrix表的matrix_height值 |no |0 |UK
|`tile_data` |BLOB | 条款<<tile_enc_png>>, <<tile_enc_jpeg>>, <<tile_enc_webp>>, <<tile_enc_tiff>>, <<tile_enc_nitf>>中定义的影像 MIME 类型。 |no | |
|=======================================================================

参见 <<example_tiles_table_sql>>.

====== 表数据取值

:tile_data_foot1: footnote:[A GeoPackage is not required to contain any tile pyramid user data tables. Tile pyramid user data tables in a GeoPackage MAY be empty.]

:tile_data_foot1_ref: footnote:[The zoom_level / tile_column / tile_row unique key is automatically indexed, and allows tiles to be selected and accessed by "z, x, y", a common convention used by some implementations.  This table / view definition MAY also allow tiles to be selected based on a spatially indexed bounding box in a separate metadata table.]

每个瓦片金字塔用户数据表或视图 {tile_data_foot1}都可以包含多个瓦片矩阵，这些瓦片矩阵对应第0级或更多缩放级别，每个缩放级别对应不同的空间分辨率（地图比例尺）。

[requirement]
在GeoPackage文件中，`gpkg_tile_matrix`(tm)表中的每个不同的`table_name`所对应的瓦片金字塔（tp）数据表中， `zoom_level`列的值应该符合以下条件：min(tm.zoom_level) <= tp.zoom_level <= max(tm.zoom_level)

[requirement]
在GeoPackage文件中，`gpkg_tile_matrix` (tm)表中的每个不同的`table_name`所对应的瓦片金字塔（tp）数据表中， tile_column列的值应该符合以下条件：当tm和tp的`zoom_level` 列值相同时，0 <= tp.tile_column <= tm.matrix_width – 1。

[requirement]
在GeoPackage文件中，`gpkg_tile_matrix` (tm)表中的每个不同的`table_name`所对应的瓦片金字塔（tp）数据表中， tile_row列的值应该符合以下条件：当tm和tp的`zoom_level` 列值相同时，0 <= tp.tile_row <= tm.matrix_height – 1。

同一缩放级别的所有瓦片都具有相同的`pixel_x_size`和`pixel_y_size`值，缩放级别对应瓦片表，以及瓦片表的`pixel_x_size`和`pixel_y_size`值是在gpkg_tile_matrix表中指定的。{tile_data_foot1_ref}