=== 元数据

==== 介绍
GeoPackage中使用两个表来存储元数据的MIME类型，以及这些MIME类型和GeoPackage中的要素、栅格和瓦片数据的关系。这两个表可以为实现ISO 19115 <<28>>中定义的分层元数据模型提供必要支持，参见Annex B B.5.25 MD_ScopeCode, <<metadata_example_appendix>> ， <<raster_or_tile_metadata_example_appendix>>。所以当新增或者更新GeoPackage中的数据时，可以单独修改与之相关的本地特定元数据，或者关联到已有的全局通用元数据。
gpkg_metadata表包含了元数据，在<<_metadata_table>>中将会进行详细的介绍。然后gpkg_metadata_reference表把gpkg_metadata表和GeoPackage中的数据关联起来，在<<_metadata_reference_table>>中会进行详细的介绍。

GeoPackage中并不要求必须提供这样的元数据或者必须以一级以上的分层结构的形式定义元数据footnote:[Informative examples of hierarchical metadata are provided in <<metadata_example_appendix>>]。但是当提供了元数据时，应该使用这些表。元数据footnote:[An informative example of raster image metadata is provided in <<tiles_example_appendix>>]以及把元数据关联到GeoPackage中内容的数据不应该保存在其它表里。

==== 元数据表

===== 数据

[[metadata_table_table_definition]]
====== 表定义

[requirement]
一个GeoPackage中可以包含一个名为gpkg_metadata的表。如果该表存在，则必须符合2.4.2.1.1 <<metadata_table_table_definition>>, <<gpkg_metadata_cols>> 和 <<gpkg_metadata_sql>>中的要求。

GeoPackage元数据的第一部分是gpkg_metadata表。该表存储官方定义的元数据标准的MIME<<21>>类型。比如ISO 19115 <<28>>, ISO 19115-2 <<B6>>, ISO 19139 <<B7>>, Dublin Core <<B8>>, CSDGM <<B10>>, DDMS <<B12>>, NMF/NMIS <<B13>>等等。在GeoPackage中，元数据是一个广义的定义，包括使用XML<<B15>>编码的UML模型<<B14>>，GML规范<<30>>，ISO 19110<<B18>>, OWL <<B20>>，SKOS <<B21>>等等。
	
:metadata_table_definition_foot1: footnote:[例如, 对于元数据ISO 19139来说，这个URI的指应该是命名空间 http://www.isotc211.org/2005/gmd]

[[gpkg_metadata_cols]]
.Metadata Table Definition
[cols=",,,,,",options="header",]
|=======================================================================
|Column Name |Column Type |Column Description |Null |Default |Key
|`id` |INTEGER |元数据主键 |no | |PK
|`md_scope` |TEXT |大小写敏感的作用域名称；参见<<metadata_scopes>> |no |‘dataset’ |
|`md_standard_uri` |TEXT |定义元数据的机构的URI <<23>> {metadata_table_definition_foot1} |no | |
|`mime_type` |TEXT |元数据的MIME <<21>>类型 |no |text/xml <<24>> |
|`metadata` |TEXT |元数据 |no |’’| 
|=======================================================================

对于一个元数据来说，md_standard_uri字段的值是其唯一标识，该标志由定义该元数据的官方机构指定。
元数据的结构信息可以使用任意的形式表示（UML <<B14>>, IDEF1x <<B16>>, XML/Schema <<25>><<26>><<27>>, RDF/S <<B19>>等等），这取决于定义元数据的机构。

参见 <<gpkg_metadata_sql>>.



====== 表数据值

表gpkg_metadata中的md_scope列是元数据对于给定行的作用域的名字。有效的作用域名及其定义参见<<metadata_scopes>>。
表的初始内容来自ISO 19115 <<40>>, 附录 B B.5.25 MD_ScopeCode编号列表。为了能在GeoPackage中使用，该列表经过了扩充footnote:[The scope codes in <<metadata_scopes>> include a very wide set of descriptive information types as “metadata” to describe data.]。增加了一个以"NA"为编号的作用域<<gpkg_metadata_cols>>。


:table_metadata_scopes_foot1: footnote:[ISO 19139 format metadata (B32) is recommended for general-purpose description of geospatial data at the series and dataset metadata scopes.]
:table_metadata_scopes_foot2: footnote:[The “catalog” md_scope MAY be used for Feature Catalog (B40) information stored as XML metadata that is linked to features stored in a GeoPackage.]
:table_metadata_scopes_foot3: footnote:[The “schema” md_scope MAY be used for Application Schema (B37)(B38)(B39)(B44) information stored as XML metadata that is linked to features stored in a GeoPackage.]
:table_metadata_scopes_foot4: footnote:[The “taxonomy” md_scope MAY be used for taxonomy or knowledge system (B41)(B42) “linked data” information stored as XML metadata that is linked to features stored in a GeoPackage.]


[[metadata_scopes]]
.元数据(Metadata)的作用域
[cols=",,",options="header",]
|=======================================================================
|名称 (md_scope) |Scope Code |含义
|undefined |NA |元信息的作用范围未定义
|fieldSession |012 |适用于字段 session 的信息
|collectionSession |004 |适用于集合 session 的信息
|series |006 |适用于(数据集)序列的信息 {table_metadata_scopes_foot1}
|dataset |005 |适用于（几何要素）数据集的信息
|featureType |010 |适用于要素类型(class)的信息
|feature |009 |适用于要素（实例）的信息
|attributeType |002 |适用于属性 class 的信息
|attribute |001 |适用于要素（实例）特性的信息
|tile |016 |适用于瓦片、地理数据空间子集的信息
|model |015 |适用于对已有对象或假设对象进行复制或模拟的信息
|catalog |NA |要素目录的元数据 {table_metadata_scopes_foot2}
|schema |NA |应用程序 schema 的元数据 {table_metadata_scopes_foot3}
|taxonomy |NA |分类系统或知识系统的元数据 {table_metadata_scopes_foot4}
|software |013 |适用于计算机软件或程序的信息
|service |014 |服务提供者实体通过一组定义行为的接口，例如用户案例，来供服务用户使用，service 表示作用于这种能力的信息
|collectionHardware |003 |适用于硬件class集合的信息
|nonGeographicDataset |007 |适用于非地理数据的信息
|dimensionGroup |008 |适用于维度群组的信息
|=======================================================================

[requirement]
在`gpkg_metadata`表或可更新视图中，每个`md_scope`列值都必须来自表<<metadata_scopes>>的'名称'列。

==== 元数据参考表

===== 数据

[[metadata_reference_table_table_definition]]
====== 表定义

[requirement]
在包含`gpkg_metadata`表的GeoPackage中，也应该包含一个`gpkg_metadata_reference`表，`gpkg_metadata_reference`表要符合 2.4.3.1.1 <<metadata_reference_table_table_definition>>, <<gpkg_metadata_reference_cols>> 和 <<gpkg_metadata_reference_sql>>的定义

GeoPackage元数据的第2个组件就是`gpkg_metadata_reference`表，它将`gpkg_metadata`表中的元数据与2.1.6和2.2.7章节定义的矢量要素数据、瓦片数据关联了起来。
表`gpkg_metadata_reference`可以没有任何记录。

:gpkg_metadata_reference_cols_foot1: footnote:[In SQLite, the rowid value is always equal to the value of a single-column primary key on an integer column [B30\] and is not changed by a database reorganization performed by the VACUUM SQL command.]

[[gpkg_metadata_reference_cols]]
.元数据参考的定义 (表名: gpkg_metadata_reference)
[cols=",,,,,",options="header",]
|=======================================================================
|Column Name |Col Type |Column Description |Null |Default |Key
|`reference_scope` |TEXT |元数据参考的作用域，取值为小写的‘geopackage’, ‘table’,‘column’, ’row’, ’row/col’之一|no | |
|`table_name` |TEXT |本元数据参考针对的表名，当`reference_scope`的值为‘geopackage’时，取值为NULL |yes | |
|`column_name` |TEXT |本元数据参考针对的列名，当`reference_scope`的值为‘geopackage’、 ‘table’ 或 ‘row’时，取值为NULL，当`reference_scope`的值为 ‘column’ 或 ‘row/col’ 时，取值为`table_name`对应的表中的列名。|yes | |
|`row_id_value` {gpkg_metadata_reference_cols_foot1} |INTEGER |当`reference_scope`的值为‘geopackage’、‘table’ 或 ‘column’ 时，取值为NULL；当`reference_scope`的值为 ‘row’ 或 ‘row/col’ 时，取值为`table_name`表中某条记录的id值。|yes | |
|`timestamp` |DATETIME |ISO 8601格式的时间戳，格式为\'%Y-%m-%dT%H:%M:%fZ'，可通过strftime函数获取当前时间。|no |strftime(\'%Y-%m-%dT%H:%M:%fZ', \'now') |
|`md_file_id` |INTEGER |本`gpkg_metadata_reference`表针对的元数据记录，用`gpkg_metadata`表的id列的值标识。|no | |FK
|`md_parent_id` |INTEGER |本`gpkg_metadata_reference`表针对的元数据记录在父`gpkg_metadata`表中对应的记录id，当 `md_file_id` 标识的就是元数据层次结构的根时，取值为NULL |yes | |FK
|=======================================================================

:gpkg_metadata_reference_null_foot1: footnote:[Such a metadata hierarchy MAY have only one level of defined metadata]

在`gpkg_metadata_reference`表中，当`md_parent_id`列的值为null时，表示该条记录就是元数据层次结构的根。{gpkg_metadata_reference_null_foot1}

参见 <<table_definition_sql>> 章节中的 <<gpkg_metadata_reference_sql>>。

====== 表数据取值

[requirement]
在`gpkg_metadata_reference`表中，`reference_scope`列的取值应该为小写的‘geopackage’, ‘table’,‘column’, ’row’, ’row/col’之一

[requirement]
在`gpkg_metadata_reference`表的记录中，当`reference_scope`列的值为‘geopackage’时，该记录的`table_name`列值应该为NULL。
其它记录的`table_name`列值应该与表`gpkg_contents`中`table_name`列的值一一对应。

[requirement]
在`gpkg_metadata_reference`表的记录中，当`reference_scope`列的值为‘geopackage’、 ‘table’ 或 ‘row’时，该记录的`column_name`列值应该为NULL。
其它记录的`column_name`列值应该为`table_name`列对应的SQLite表或视图中的一个列名。

[requirement]
在`gpkg_metadata_reference`表的记录中，当`reference_scope`列的值为‘geopackage’、‘table’ 或 ‘column’时，该记录的`row_id_value`列值应该为NULL。
其它记录的`row_id_value`列值应该为`table_name`列对应的SQLite表或视图中的某条记录的id值（ROWID）。

:req_75_foot1: footnote:[The following statement selects an ISO 8601timestamp value using the SQLite strftime function: SELECT (strftime('%Y-%m-%dT%H:%M:%fZ','now')).]
[requirement]
在`gpkg_metadata_reference`表的记录中，`timestamp` 列的取值应该符合ISO 8601 <<29>>规范，应该是一个包含UTC 小时, 分钟, 秒，以及秒的小数部分的完整的日期字符串，并应该带有‘Z’ (‘zulu’)后缀来标识时间为协调世界时（UTC）。{req_75_foot1}

[requirement]
在`gpkg_metadata_reference`表的记录中，`md_file_id`列的值应该来自`gpkg_metadata`表的id列。

[requirement]
在`gpkg_metadata_reference`表的记录中，当`md_parent_id`列的取值不为NULL时，取值应该来自`gpkg_metadata`表的id列，并且与同一记录中的`md_file_id`列的值不同。