[[registered_extensions]]
== 已注册的扩展

本章节规定了GeoPackage扩展的必要条款。
这些扩展是基于 <<extension_template>> 中的模板定义的，在附录J-P中可以找到它们的定义。
 
=== 要素

在包含<<features>>章节定义的要素的GeoPackage中，可以实现如下子章节定义的扩展。

[[gpkg_geometry_types_extension]]
==== GeoPackage 几何类型扩展

===== 数据

本扩展定义了附加的几何类型，是<<sql_geometry_types>>章节的扩展，在<<extension_geometry_types>>中做了部分描述。

====== 扩展类型

[requirement]
在GeoPackage中，几何要素表中的几何类型可以是<<geometry_types>>中所列的扩展非线性的几何类型（CircularString, CompoundCurve, CurvePolygon, MultiCurve, MultiSurface, Curve, Surface）。
此时，几何对象必须使用GeoPackageBinary几何对象格式进行编码。

====== 扩展类型 - 扩展名称

[requirement]
定义一个几何要素扩展类型时，扩展名称中的作者名应该是“gpkg”，即使用“gpkg_geom_<gname>”模板，其中<gname>是扩展几何类型，取值为GeoPackage中使用的<<geometry_types>>之一，全大写表示。

====== 扩展类型 - 扩展记录

[requirement]
在包含 gpkg_geometry_columns 表/可更新视图的GeoPackage中，如果 gpkg_geometry_columns 表包含 geometry_type_name 列值为扩展类型的记录，那么该GeoPackage中也必须包含一个 gpkg_extensions 表，gpkg_extensions 表的部分（全部）记录的table_name 和 column_name 列值应该来自 gpkg_geometry_columns 表，用来标识扩展类型的使用范围，这些记录的extension_name列值应该涵盖 3.1.1.1.2 章节定义的几何类型。

[[gpkg_user_geometry_types_extension]]
==== 用户自定义几何类型的扩展

===== 数据

本扩展定义了在扩展的GeoPackage中，对用户自定义几何类型使用ExtendedGeoPackageBinary格式进行编码的规范，是对<<gpb_format>>, <<sql_geometry_types>> 和 <<gpkg_geometry_types_extension>> 章节的扩展，在<<extension_geometry_encoding>>中做了部分描述。

====== 编码格式扩展

[requirement]
ExtendedGeoPackageBinary格式由<<extension_geometry_encoding>>定义，用于对用户自定义几何类型进行编码，该格式不能用来编码如下几何类型：在 <<sql_geometry_types>> 中定义的几何类型、在 <<gpkg_geometry_types_extension>> 中定义的几何类型、以及<<geometry_types>>中所列出的几何类型。

====== 编码格式扩展 - 扩展名称

[[user_defined_geometry_ext_name_req]]
[requirement]
定义一个使用ExtendedGeoPackageBinary格式进行编码的几何对象扩展类型时，扩展名称按照模板“<author_name>_geom_<gname>”定义，其中的作者名(<author_name>)不能为“gpkg”，<gname>是GeoPackage中使用的扩展几何类型的名称，取值不能与<<geometry_types>>列出的相同，且必须全大写。

====== 编码格式扩展 - 扩展记录

[requirement]
在包含 gpkg_geometry_columns 表/可更新视图的扩展GeoPackage中，如果 gpkg_geometry_columns 表包含 geometry_type_name 列值为扩展类型的记录，且这些类型不是在<<sql_geometry_types>> 和 3.1.1定义的类型，也没有包含在<<geometry_types>>中，那么该扩展的GeoPackage中也必须包含一个 gpkg_extensions 表，gpkg_extensions 表的部分（全部）记录的table_name 和 column_name 列值应该来自 gpkg_geometry_columns 表，用来标识扩展类型的使用范围，这些记录的 extension_name 列值应该涵盖 3.1.1.1.2 章节定义的几何类型。

====== 几何对象列的几何类型名称

[requirement]
`gpkg_geometry_columns`表的记录中，`geometry_type_name`表示扩展名称，它的取值必须符合<<user_defined_geometry_ext_name_req>>的定义，且为全大写形式。

==== R树空间索引

===== 数据

本扩展增加了一种新的建立空间索引的能力，适用于根据 <<gpb_format>> 和 <<gpkg_user_geometry_types_extension>> 章节存储几何对象的列，在<<extension_rtree>>中做了部分描述。

====== 空间索引的实现

:spatial_indexes_impl_foot1: footnote:[If an application process will make many updates, it is often faster to drop the indexes, do the updates, and then recreate the indexes.]

在针对包含海量（几千或更多）记录的要素表进行基本的空间框选搜索，返回要素子集时，空间索引能极大提高搜索性能。{spatial_indexes_impl_foot1}

[requirement]
按照3.1.3.1.1规定，GeoPackage应该使用<<extension_rtree>>中指定的SQLite Virtual Table RTrees和触发器，来为要素表中的几何对象列建立空间索引。

====== 空间索引 - 扩展名

[requirement]
在gpkg_extensions表中，扩展名为“gpkg_rtree_index”的记录用来指定几何对象列的空间索引实现。

====== 空间索引 - 扩展记录

[requirement]
在实现空间索引的GeoPackage中，应该包含一个gpkg_extensions表，且在gpkg_extensions表中，针对每一个建立空间索引的列，都应该有一条extension_name列值为“gpkg_rtree_index”的记录与之对应，该条记录的table_name值对应的表中必须包含一个建立空间索引的列，该条记录的column_name值对应的列必须是一个建立了空间索引的列。

==== 几何类型触发器

===== 数据

本扩展增加了一种新的几何类型触发器（geometry type triggers），适用于根据 <<gpb_format>> 和 <<gpkg_user_geometry_types_extension>> 章节存储几何对象的列，在<<extension_geometry_type_triggers>>中做了部分描述。

====== 几何类型触发器 – 实现

[requirement]
在GeoPackage中，为确保几何对象列对应的几何类型在gpkg_geometry_columns表中都被指定，针对每个几何对象列都应该包含SQL插入和更新的触发器，触发器由<<extension_geometry_type_triggers>>定义。

====== 几何类型触发器 – 扩展名

[requirement]
在gpkg_extensions表中，扩展名为“gpkg_geometry_type_trigger”的记录用来指定几何类型触发器的实现。

====== 几何类型触发器 – 扩展记录

[requirement]
在实现了几何类型触发器的GeoPackage中，应该包含一个gpkg_extensions表，且在gpkg_extensions表中，针对每一个几何类型触发器对应的几何对象列，都应该有一条extension_name列值为“gpkg_geometry_type_trigger”的记录与之对应，该条记录的table_name值对应的要素表中必须包含一个几何对象列，该条记录的column_name值对应的列存储的必须是几何对象。

==== SRS_ID 触发器

===== 数据
针对根据 <<gpb_format>> 和 <<gpkg_user_geometry_types_extension>>进行编码的几何对象列，本扩展对其添加了一个新的 srs_id 触发器，该触发器由<extension_geometry_srsid_triggers>定义。

====== SRS_ID 触发器– 实现

[requirement]

在GeoPackage 的每个几何列上应该包括在 <<extension_geometry_srsid_triggers>>中指定的SQL 插入和更新的触发器，用于同步`gpkg_geometry_columns` 表中对应列的srs_id值。

====== SRS_ID 触发器 – 扩展名

[requirement]

在gpkg_extensions表中，扩展名为“gpkg_srs_id_trigger” 的记录用来指定SRS_ID触发器的实现。该值是在<extension_geometry_srsid_triggers>中进行指定的。 

====== SRS_ID 触发器 – 扩展记录

[requirement]

如果GeoPackage实现了要素表几何列的srs_id触发器，那么就应该包含一个gpkg_extensions 扩展表，该扩展表中针对每一个要素几何列的触发器对应的几何对象列，都应该有一条extension_name列值为“gpkg_srs_id_trigger”的记录与之对应，该条记录的table_name值对应的要素表中必须包含一个几何对象列，该条记录的column_name值对应的列存储的必须是几何对象。

=== 瓦片

下面子句中定义的扩展，可能在实现了每个<tiles>句子的GeoPackage 中被实现。

==== 缩放级别

===== 数据

在<<extension_zoom_other_intervals>>中描述的<<zoom_levels>>句子扩展，允许多级缩放。

====== 其他缩放间隔
在相邻级别缩放时，瓦片金字塔数据表中的像素大小可能按不规则的间隔变化，也可能按非2倍缩放（默认）的规则间隔变化

====== 其他缩放 – 扩展名

[requirement]
在gpkg_extensions表中，扩展名为“gpkg_zoom_other”的记录是用来实现多级缩放。其缩放级别在<< extension_zoom_other_intervals>>金字塔用户数据表中指定。

====== 其他缩放 – 扩展记录

[requirement]
实现多级缩放的GeoPackage应包含一个扩展表gpkg_extensions，该扩展表中针对每一个多级缩放列对应的多级缩放对象列，都应该有一条extension_name列值为"gpkg_zoom_other"的记录与之对应，该条记录的table_name值对应的要素表中必须包含一个多级缩放对象列，该条记录的column_name值对应的列存储的必须由多级缩放对象构成的瓦片金字塔用户数据。

[[tile_enc_webp]]
==== WEBP瓦片编码格式

===== 数据

此条款扩展了<<tile_enc_png>> 和 <<tile_enc_jpeg>>，允许瓦片图像以 WebP 格式进行编码，该扩展在<<extension_tiles_webp>> 中进行了描述

===== WEBP MIME 类型

在包含瓦片金字塔用户数据表的GeoPackage中，tile_data存储的瓦片数据可以是image/x-web <<22>>MIME类型。


====== WEBP -- 扩展名

[requirement]
在gpkg_extensions表中，扩展名为"gpkg_webp" 的记录用来指定瓦片金字塔影像的存储格式为WEBP格式，WEBP格式由<<extension_tiles_webp>>定义。

====== WEBP -- 扩展记录

[requirement]
在包含瓦片金字塔数据表的GeoPackage中，如果数据表的title_data列存储的影像为WEBP格式，那么该GeoPackage应该包含一个 gpkg_extensions 表，针对上述的瓦片金字塔数据表，都应该能通过table_name在gpkg_extensions 表中找到对应的记录，并且这些记录的column_name列值应该为“tile_data”，extension_name列值应该为“gpkg_webp”。